### ISSUE TITLE
攻击优化调整

### ISSUE THREAD

**Issue by Shelock123** [lazydog28/mc_auto_boss#1]
加一个E技能释放，和空中跳跃攻击会很好（触发治疗效果）

**Comment by lazydog28** [comment]
E技能释放已经有了，空中跳跃攻击需求不是很强，切人或者被攻击都会有可能在空中，此时攻击就能触发空中攻击

**Comment by Shelock123** [comment]
O(∩_∩)O哈哈~，空中跳跃攻击主要是：维里奈可以一次性消耗掉阳光，达到治疗的最佳效果
