### ISSUE TITLE
这是什么问题啊大佬

### ISSUE THREAD

**Issue by lyChara** [lazydog28/mc_auto_boss#103]
![微信图片_20240619214415](https://github.com/lazydog28/mc_auto_boss/assets/67398370/5812cc6c-d429-4f6b-b645-cb51250a328f)

**Comment by Golorcsh** [comment]
config.example.yaml模板的问题，你把自己的config.yaml修改一下，删除多余的符号
![PixPin_2024-06-19_22-05-16](https://github.com/lazydog28/mc_auto_boss/assets/27144246/63de5d2a-cff8-4142-ac72-48fc1ed28b1b)

**Comment by RoseRin0** [comment]
> config.example.yaml模板的问题，你把自己的config.yaml修改一下，删除多余的符号 ![PixPin_2024-06-19_22-05-16](https://private-user-images.githubusercontent.com/27144246/341105607-63de5d2a-cff8-4142-ac72-48fc1ed28b1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MDY4MjEsIm5iZiI6MTcxODgwNjUyMSwicGF0aCI6Ii8yNzE0NDI0Ni8zNDExMDU2MDctNjNkZTVkMmEtY2ZmOC00MTQyLWFjNzItNDhmYzFlZDI4YjFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDE0MTUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxM2U0YjQ5MzhmYjAzZWY0MWY1MTg4MjliYzQ0YTlkYzEwNDM0MDk4MjBkZmY5NzJiYjlmMGMyMmI1NTY4ZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NaS780qo0O3kfbQzOaFv7qy4gOuWuK0Lcv54Aa85Etk)

直接把写在config.py的给复制过去了，忘记改了，感谢纠错

**Comment by lyChara** [comment]
解决了，感谢  我运行的时候出错了，是我搭建环境的问题吗
![微信图片_20240619223845](https://github.com/lazydog28/mc_auto_boss/assets/67398370/aad2e06d-71cb-4e72-b154-c3e1de1f5d34)

**Comment by lazydog28** [comment]
没装CUDA

[GPU环境搭建](https://github.com/lazydog28/mc_auto_boss/wiki/GPU%E7%8E%AF%E5%A2%83%E6%90%AD%E5%BB%BA)
