### ISSUE TITLE
四循环刷声骸（3boss+无妄者）

### ISSUE THREAD

**Issue by Miracy9** [lazydog28/mc_auto_boss#11]
大佬，您做的太好了！！谢谢！！已经用上了，但是想要提一点点小建议：
现在刷boss是三锚点循环，但是我觉得随着大家的连度逐渐增加（或者说会降世界等级刷boss），我经常会遇到应为刷boss太快导致频繁的在地图上传送，因此我希望大佬您能抽时间搞一个三世界boss+无妄者的四循环刷声骸，这样效率应该会高很多，也不会出现频繁的传送了。最后，大佬辛苦了！！！谢谢大佬！！

**Comment by lazydog28** [comment]
dev分支当前已添加该功能，在配置文件中目标BOSS填写无妄者即可

**Comment by Miracy9** [comment]
大佬辛苦了，dev版本的我今天上午用了一下，效率高出不少，而且加了识别声骸和转向，现在吸取声骸概率基本可以100%了，但是好像有一个小bug，我用正式版的时候就是使用的gpu加速，但是到测试版就只能用cpu，我也把dev版本中的requestments-gpu.txt重新装了一遍，还是不行。下面是任务管理器的截图：
![1](https://github.com/lazydog28/mc_auto_boss/assets/106250543/5a9f08ef-f1e6-44e7-bac2-63e1794dfa2f)

**Comment by lazydog28** [comment]
代码里忘记使用GPU加速了
