### ISSUE TITLE
RuntimeError: (PreconditionNotMet) The third-party dynamic library (cudnn64_8.dll) that Paddle depends on is not configured correctly.

### ISSUE THREAD

**Issue by ChesterGuo** [lazydog28/mc_auto_boss#110]
[](url
<img width="937" alt="屏幕截图 2024-06-21 005010" src="https://github.com/lazydog28/mc_auto_boss/assets/13127595/ef270606-768b-4198-8d65-cc1868e1e41b">
这是代码有问题吗

**Comment by lazydog28** [comment]
没装CUDA

[GPU环境搭建](https://github.com/lazydog28/mc_auto_boss/wiki/GPU%E7%8E%AF%E5%A2%83%E6%90%AD%E5%BB%BA)
