### ISSUE TITLE
启动出现问题求教

### ISSUE THREAD

**Issue by Future-FoXe** [lazydog28/mc_auto_boss#112]
环境配好了，启动报错：
>(mc) PS E:\Games\GameTools\mc_auto_boss-gpu> python .\background\main.py
Traceback (most recent call last):
  File "E:\Games\GameTools\mc_auto_boss-gpu\background\main.py", line 6, in <module>
    from mouse_reset import mouse_reset
  File "E:\Games\GameTools\mc_auto_boss-gpu\background\mouse_reset.py", line 12, in <module>
  File "E:\Games\GameTools\mc_auto_boss-gpu\background\status.py", line 11, in <module>
    from config import config
  File "E:\Games\GameTools\mc_auto_boss-gpu\background\config.py", line 14, in <module>
    class Config(BaseModel):
  File "D:\ProgramData\miniconda3\envs\mc\lib\site-packages\pydantic\_internal\_model_construction.py", line 93, in __new__
    private_attributes = inspect_namespace(
  File "D:\ProgramData\miniconda3\envs\mc\lib\site-packages\pydantic\_internal\_model_construction.py", line 406, in inspect_namespace
    raise PydanticUserError(
pydantic.errors.PydanticUserError: A non-annotated attribute was detected: `project_root = 'E:\\Games\\GameTools\\mc_auto_boss-gpu\\background'`. All model fields require a type annotation; if `project_root` is not meant to be a field, you may be able to resolve this error by annotating it as a `ClassVar` or updating `model_config['ignored_types']`.
For further information visit https://errors.pydantic.dev/2.7/u/model-field-missing-annotation

其它一点信息：
> (mc) PS E:\Games\GameTools\mc_auto_boss-gpu> python
Python 3.10.14 | packaged by Anaconda, Inc. | (main, May  6 2024, 19:44:50) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ...
I0621 10:14:49.354347 26612 program_interpreter.cc:212] New Executor is Running.
W0621 10:14:49.356846 26612 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.5, Runtime API Version: 11.7
W0621 10:14:49.367237 26612 gpu_resources.cc:164] device: 0, cuDNN Version: 8.4.
I0621 10:14:53.306748 26612 interpreter_util.cc:624] Standalone Executor is Used.
PaddlePaddle works well on 1 GPU.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.

**Comment by lazydog28** [comment]
https://github.com/lazydog28/mc_auto_boss/blob/0e391f255e392910cd7d06d6bcfe22d568808c99/background/config.py#L44


看报错信息是因为 `project_root`  没有类型注释，你看一下你的`E:\Games\GameTools\mc_auto_boss-gpu\background\config.py`里`project_root`有类型注释嘛

**Comment by Future-FoXe** [comment]
> https://github.com/lazydog28/mc_auto_boss/blob/0e391f255e392910cd7d06d6bcfe22d568808c99/background/config.py#L44
> 
> 看报错信息是因为 没有类型注释，你看一下你的里有类型注释嘛`project_root``E:\Games\GameTools\mc_auto_boss-gpu\background\config.py``project_root`

搞了注释可以启动了，又尝试重新cd一次项目也没以上报错，看了眼时间好像是后来有文件改动，不知道和这个原因有没有关系。感谢
