### ISSUE TITLE
优化建议:定时重启游戏，防止长时间挂机而导致游戏崩溃，而导致脚本结束运行

### ISSUE THREAD

**Issue by wang115t** [lazydog28/mc_auto_boss#113]

**Comment by wang115t** [comment]
![Uploading Snipaste_2024-06-21_13-58-01.png…]()

**Comment by Miracy9** [comment]
我自己改了一个版本的可以两个小时定时重启的，只需要替换main.py和在general.py里面添加一段代码就行，需要修改main里面的app_path,改成游戏的窗口启动路径，不是启动器路径。重启间隔也是在main.py里面修改，里面有注释的提示。用了两天效果还可以。附件里面有需要替换的main.py和需要增加的general.py的代码
[附件.zip](https://github.com/user-attachments/files/15925103/default.zip)

**Comment by wang115t** [comment]
> 我自己改了一个版本的可以两个小时定时重启的，只需要替换 main.py 和在 general.py 里面添加一段代码就行，需要修改main里面的app_path，改成游戏的窗口启动路径，不是启动器路径。重启间隔也是在 main.py 里面修改，里面有注释的提示。用了两天效果还可以。附件里面有需要替换的 main.py 和需要增加的 general.py 的代码 [附件.zip](https://github.com/user-attachments/files/15925103/default.zip)

非常感谢！
