### ISSUE TITLE
AMD显卡不能用吗？

### ISSUE THREAD

**Issue by yellowredhh** [lazydog28/mc_auto_boss#121]
老久之前下载的老版本，可以跑起来，当时也是AMD显卡，是使用CPU进行图像识别的
最近拉了下最新版代码，发现我电脑用不了，最新版不能使用CPU识别图像了，强制要求GPU，怎么办？

**Comment by lazydog28** [comment]
不是有个 requirements_cpu.txt 嘛？

**Comment by katsuraDaCn** [comment]
> 不是有个 requirements_cpu.txt 嘛？

运行这个a卡也能用这个版本了吗？那还要不要安装gpu环境？

**Comment by lazydog28** [comment]
用不了GPU就不用安装GPU环境
