### ISSUE TITLE
关于新版本配置文件 游戏路径报错的问题

### ISSUE THREAD

**Issue by 1103962721** [lazydog28/mc_auto_boss#122]
![CMD窗口](https://github.com/lazydog28/mc_auto_boss/assets/74693644/961aed4f-91fb-4630-b838-0e87817beebd)
![config](https://github.com/lazydog28/mc_auto_boss/assets/74693644/0db182ae-28f9-4a82-a776-30e14e374e35)
![鸣潮目录](https://github.com/lazydog28/mc_auto_boss/assets/74693644/e3c167ba-34db-49a6-9f0d-96e1d850e135)
![文件目录](https://github.com/lazydog28/mc_auto_boss/assets/74693644/0c8f6d60-b7ee-48c8-a5dd-4145c743d114)

**Comment by lazydog28** [comment]
新版本修复了该问题
