### ISSUE TITLE
2024年6月22日23:57:49 F8快捷键keycode报错

### ISSUE THREAD

**Issue by 1103962721** [lazydog28/mc_auto_boss#124]
![image](https://github.com/lazydog28/mc_auto_boss/assets/74693644/cb7b0e20-a996-41ec-92f2-ccfddf237dfd)

**Comment by RoseRin0** [comment]
> ![image](https://private-user-images.githubusercontent.com/74693644/341981859-cb7b0e20-a996-41ec-92f2-ccfddf237dfd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNzIzOTUsIm5iZiI6MTcxOTA3MjA5NSwicGF0aCI6Ii83NDY5MzY0NC8zNDE5ODE4NTktY2I3YjBlMjAtYTk5Ni00MWVjLTkyZjItY2NmZGRmMjM3ZGZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDE2MDEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlNWI3YzE1NzVjNjM3OGQ4N2ZkM2RiZWEyNGU4NjY4YjNkZTNkY2FmZmEwMDZhMTE5YzdkZGZiOWVjMzMwMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yilTHK8Vq6vjjrzEKVJuwJy1mox_x19zjFvCgYfvSLE)

![image](https://github.com/lazydog28/mc_auto_boss/assets/123860230/d6050177-a419-44cb-a5a5-75b1cac01916)
白天已经在更新里面标注这个的解决方法了，
并且，这个更新我已经pr了，只是作者还没merge。

**Comment by 1103962721** [comment]
> > ![image](https://private-user-images.githubusercontent.com/74693644/341981859-cb7b0e20-a996-41ec-92f2-ccfddf237dfd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNzIzOTUsIm5iZiI6MTcxOTA3MjA5NSwicGF0aCI6Ii83NDY5MzY0NC8zNDE5ODE4NTktY2I3YjBlMjAtYTk5Ni00MWVjLTkyZjItY2NmZGRmMjM3ZGZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDE2MDEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlNWI3YzE1NzVjNjM3OGQ4N2ZkM2RiZWEyNGU4NjY4YjNkZTNkY2FmZmEwMDZhMTE5YzdkZGZiOWVjMzMwMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yilTHK8Vq6vjjrzEKVJuwJy1mox_x19zjFvCgYfvSLE)
> 
> ![image](https://private-user-images.githubusercontent.com/123860230/341982152-d6050177-a419-44cb-a5a5-75b1cac01916.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNzI4MDUsIm5iZiI6MTcxOTA3MjUwNSwicGF0aCI6Ii8xMjM4NjAyMzAvMzQxOTgyMTUyLWQ2MDUwMTc3LWE0MTktNDRjYi1hNWE1LTc1YjFjYWMwMTkxNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMlQxNjA4MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMmM1OTI4MjQ3OTA1Y2JlNjc1YTMyYTViNzZmMDc5NDczZWRlOTIxODhlMzJmNThlOWZmZTk4MjE2ZWE4MzAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PUYTEZQUkhF64lvPtH2o8uevzKHKdMI1G26lLAS3OXo) 白天已经在更新里面标注这个的解决方法了， 并且，这个更新我已经pr了，只是作者还没merge。

感谢

**Comment by 1103962721** [comment]
> > ![image](https://private-user-images.githubusercontent.com/74693644/341981859-cb7b0e20-a996-41ec-92f2-ccfddf237dfd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNzIzOTUsIm5iZiI6MTcxOTA3MjA5NSwicGF0aCI6Ii83NDY5MzY0NC8zNDE5ODE4NTktY2I3YjBlMjAtYTk5Ni00MWVjLTkyZjItY2NmZGRmMjM3ZGZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDE2MDEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlNWI3YzE1NzVjNjM3OGQ4N2ZkM2RiZWEyNGU4NjY4YjNkZTNkY2FmZmEwMDZhMTE5YzdkZGZiOWVjMzMwMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yilTHK8Vq6vjjrzEKVJuwJy1mox_x19zjFvCgYfvSLE)
> 
> ![image](https://private-user-images.githubusercontent.com/123860230/341982152-d6050177-a419-44cb-a5a5-75b1cac01916.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNzM5MzQsIm5iZiI6MTcxOTA3MzYzNCwicGF0aCI6Ii8xMjM4NjAyMzAvMzQxOTgyMTUyLWQ2MDUwMTc3LWE0MTktNDRjYi1hNWE1LTc1YjFjYWMwMTkxNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMlQxNjI3MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZmMyNGE0OWFmYzg0YjhhNWFiNjIyZTY2M2MwNTZhZDVhZTE5ODgxNDM3OTQ5OTQ0OTYxNmRjMmFiODMwY2U5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RZmVw1VjyPTJK5Yokqi2QyAbYL5PF3HndpXVHgHlcKo) 白天已经在更新里面标注这个的解决方法了， 并且，这个更新我已经pr了，只是作者还没merge。

**Comment by 1103962721** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/74693644/341981859-cb7b0e20-a996-41ec-92f2-ccfddf237dfd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNzIzOTUsIm5iZiI6MTcxOTA3MjA5NSwicGF0aCI6Ii83NDY5MzY0NC8zNDE5ODE4NTktY2I3YjBlMjAtYTk5Ni00MWVjLTkyZjItY2NmZGRmMjM3ZGZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDE2MDEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlNWI3YzE1NzVjNjM3OGQ4N2ZkM2RiZWEyNGU4NjY4YjNkZTNkY2FmZmEwMDZhMTE5YzdkZGZiOWVjMzMwMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yilTHK8Vq6vjjrzEKVJuwJy1mox_x19zjFvCgYfvSLE)
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/123860230/341982152-d6050177-a419-44cb-a5a5-75b1cac01916.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNzM5MzQsIm5iZiI6MTcxOTA3MzYzNCwicGF0aCI6Ii8xMjM4NjAyMzAvMzQxOTgyMTUyLWQ2MDUwMTc3LWE0MTktNDRjYi1hNWE1LTc1YjFjYWMwMTkxNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMlQxNjI3MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZmMyNGE0OWFmYzg0YjhhNWFiNjIyZTY2M2MwNTZhZDVhZTE5ODgxNDM3OTQ5OTQ0OTYxNmRjMmFiODMwY2U5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RZmVw1VjyPTJK5Yokqi2QyAbYL5PF3HndpXVHgHlcKo) 白天已经在更新里面标注这个的解决方法了， 并且，这个更新我已经pr了，只是作者还没merge。

老哥 麻烦问一下这个F8是怎么用的 我在使用F8后出现2024-06-23 00:23:31 战斗次数：0 吸收次数：0 治疗次数：0 未启动该功能声骸锁定功能结束或异常退出，结束脚本

**Comment by RoseRin0** [comment]
复制echo_config.example.yaml到echo_config.yaml并修改相关内容，然后在config.yaml打开相关选项，在背包声骸页面按F8，目前有些分辨率好用有些分辨率不好用。

**Comment by 1103962721** [comment]
> 复制echo_config.example.yaml到echo_config.yaml并修改相关内容，然后在config.yaml打开相关选项，在背包声骸页面按F8，目前有些分辨率好用有些分辨率不好用。
![image](https://github.com/lazydog28/mc_auto_boss/assets/74693644/db8a4c07-1292-421f-9e92-c10c1b03517d)

![image](https://github.com/lazydog28/mc_auto_boss/assets/74693644/afcde647-0e83-4505-a016-c56b28754c64)

![image](https://github.com/lazydog28/mc_auto_boss/assets/74693644/23f8928e-aa98-461a-8280-1e0ca972f60a)

可能还是有些BUG 感谢分享 话说main里面默认每秒去检测窗口判断游戏是否掉线 这个会不会占用太大了
