### ISSUE TITLE
报错问题

### ISSUE THREAD

**Issue by hecatekuroyuki** [lazydog28/mc_auto_boss#127]
不知道这个问题该怎么解决。求助一下各位
![image](https://github.com/lazydog28/mc_auto_boss/assets/136726333/539f224e-8f00-45ff-9106-0440735b1f86)

**Comment by Leaf1208** [comment]
config.example.yaml 更改成config.yaml  AppPath:添加遊戲路徑就可以用了
剛剛也遇到

**Comment by hecatekuroyuki** [comment]
> config.example.yaml 更改成config.yaml  AppPath:添加遊戲路徑就可以用了
> 
> 剛剛也遇到

好的非常感谢 旧版都是自动添加config.yaml的 下意识以为不是这个原因
