### ISSUE TITLE
F8识别胚子运行不正常

### ISSUE THREAD

**Issue by Tasikaio** [lazydog28/mc_auto_boss#133]
![image](https://github.com/lazydog28/mc_auto_boss/assets/56103657/911713db-1082-4626-b12b-c26699579655)
一直判定不是金色品质

另外，在游戏分辨率为1280x720时，会出现如下报错
![image](https://github.com/lazydog28/mc_auto_boss/assets/56103657/1f53dddb-71da-4f0b-991c-d5378bf97686)
![image](https://github.com/lazydog28/mc_auto_boss/assets/56103657/1ef72f4f-d61c-4ed0-90d2-c3d4540a5c76)

**Comment by RoseRin0** [comment]
适配写好了，正在测试，测试完了会上传的，等吧

**Comment by Tasikaio** [comment]
ok,感谢大大让我少坐牢

**Comment by RoseRin0** [comment]
#134 已PR，待合并
