### ISSUE TITLE
寻找声骸时，有时识别不到

### ISSUE THREAD

**Issue by Sun5043** [lazydog28/mc_auto_boss#136]
甚至有时角色正对声骸，但仍然未识别到，然后没有吸收声骸就传走了

**Comment by Sun5043** [comment]
而且有时距离声骸比较远，即使识别到了，角色向前挪动几步后，再次识别就识别不到了

**Comment by RoseRin0** [comment]
目前这个问题没有什么好的解决办法，建议是在连招中穿插f按键，BOSS死亡时第一时间按键吸取（不过此种方法脚本不会计数）

**Comment by Sun5043** [comment]
可能是画面设置的问题，把人物距离调整到0（也就是最近距离）以后，体验好很多

**Comment by RoseRin0** [comment]
好的 感谢反馈

**Comment by yeming1999** [comment]
经验证，将战斗、探索的镜头距离改为0后，之前走几步就识别不到声骸的情况已经解决。
