### ISSUE TITLE
关于声骸锁定功能的使用情况

### ISSUE THREAD

**Issue by yeming1999** [lazydog28/mc_auto_boss#138]
前言：
1、需要将内容，存放在echo_config.yaml、echo_config.example.yaml两个文件下，内容可参考：
# 请配置你所需要的套装、Cost、以及其对应属性
          EchoLockConfig:
            凝夜白霜:
              1COST: ["攻击", "生命"]
              3COST: ["共鸣效率", "冷凝伤害加成"]
              4COST: ["暴击", "暴击伤害"]
            熔山裂谷:
              1COST: ["攻击"]
              3COST: ["共鸣效率", "热熔伤害加成"]
              4COST: ["攻击", "暴击", "暴击伤害"]
            彻空冥雷:
              1COST: ["攻击"]
              3COST: ["共鸣效率", "导电伤害加成"]
              4COST: ["暴击", "暴击伤害"]
            啸谷长风:
              1COST: ["攻击"]
              3COST: ["共鸣效率", "气动伤害加成"]
              4COST: ["暴击", "暴击伤害"]
            浮星祛暗:
              1COST: ["攻击"]
              3COST: ["共鸣效率", "衍射伤害加成"]
              4COST: ["暴击", "暴击伤害"]
            沉日劫明:
              1COST: ["攻击"]
              3COST: ["共鸣效率", "湮灭伤害加成"]
              4COST: ["暴击", "暴击伤害"]
            隐世回光:
              1COST: ["攻击", "生命"]
              3COST: ["共鸣效率"]
              4COST: ["治疗效果加成"]
            轻云出月:
              1COST: ["攻击"]
              3COST: ["共鸣效率"]
              4COST: ["暴击", "暴击伤害"]
2、需要在角色->声骸->点击任意声骸->确定”简述“功能为开启（此时声骸技能会显示具体的伤害数值）
3、需要config.example.yaml、config.yaml 两个配置文件开启声骸锁功能，
          EchoLock: true #是否使用启用声骸锁定功能  （实验功能）
          EchoMaxContinuousLockQuantity: 5 # 最大连续检测到已锁定声骸的数量，超过此数量就停止
4、F8运行，经验证60+声骸按照预计进行了锁定
5、遇到的问题：在开启声骸锁定后，摁下F7并没有暂停，而是过了几秒又启动了声骸锁定

**Comment by RoseRin0** [comment]
声骸锁定和合成的时候暂停不可用。
