### ISSUE TITLE
报错：TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by libinrui-lbr** [lazydog28/mc_auto_boss#139]
![QQ截图20240627161056](https://github.com/lazydog28/mc_auto_boss/assets/153591160/c904b5b6-e98e-4708-94c5-bbe5879eed70)

**Comment by lazydog28** [comment]
新版本
8c59ccf0b72e88c3ddc26b485e0f530cf4b756da
修复了该问题
