### ISSUE TITLE
吸收声骸失败，以及无妄者卡在选择等级上面

### ISSUE THREAD

**Issue by jadehand** [lazydog28/mc_auto_boss#14]
[Desktop.zip](https://github.com/user-attachments/files/15535757/Desktop.zip)

**Comment by jadehand** [comment]
> readme中有说明，游戏窗口仅支持16:9分辨率,屏幕缩放为100%，推荐分辨率为1280x720，不建议全屏

调了，还是一样的问题
![image](https://github.com/lazydog28/mc_auto_boss/assets/99817629/3d976c9d-2769-45c9-aeb0-5de63037a27c)

**Comment by lazydog28** [comment]
进群找群主，我远程帮你看一下
