### ISSUE TITLE
游戏更新到1.1后 脚本貌似无法识别    - "无妄者"

### ISSUE THREAD

**Issue by 18664249165** [lazydog28/mc_auto_boss#145]
游戏更新到1.1后 脚本貌似无法识别    - "无妄者"

![screenshot-1719563368485](https://github.com/lazydog28/mc_auto_boss/assets/58971072/3a7ff931-1aa9-43c6-9572-f3be6ff1abdf)

**Comment by lazydog28** [comment]
bf90b4c453920c1a469ce8f966ebd7d6fb67f69a

已更新
