### ISSUE TITLE
与新boss"角"战斗时无法判定战斗状态 角色原地罚站

### ISSUE THREAD

**Issue by ArcS17** [lazydog28/mc_auto_boss#147]
![2428b2c60feed2f90fc4496168525f87](https://github.com/lazydog28/mc_auto_boss/assets/94548426/72969166-22c4-46a9-b1bf-d6b5343dc7ce)
新boss"角"的战斗页面不再是击败(boss名)而是与角对战, 特征字可能需要更改

**Comment by lazydog28** [comment]
已经更新该部分
