### ISSUE TITLE
新版本又出现卡月卡了

### ISSUE THREAD

**Issue by Yunako229** [lazydog28/mc_auto_boss#154]
![Uploading 1a5a648c-5a04-4bd0-bcd7-ebb25e179c1a.png…]()

**Comment by Yunako229** [comment]
![Uploading 1a5a648c-5a04-4bd0-bcd7-ebb25e179c1a.png…]()

**Comment by Yunako229** [comment]
![1a5a648c-5a04-4bd0-bcd7-ebb25e179c1a](https://github.com/lazydog28/mc_auto_boss/assets/84826080/fecd0ea7-a391-440b-91db-6e3dc8f7cb26)

**Comment by lazydog28** [comment]
好的，已经修复
