### ISSUE TITLE
只刷角，传送后会直接开始战斗，而不是点进入副本

### ISSUE THREAD

**Issue by czc2912** [lazydog28/mc_auto_boss#156]
只刷角，传送后会直接开始战斗，而不是点进入副本，容易导致掉下悬崖。

**Comment by czc2912** [comment]
掉下悬崖后，最大战斗时间也没有生效，一直在打空气

**Comment by lazydog28** [comment]
测试没有发现这种情况，麻烦提供一下录制的视频。
判断是否需要战斗是根据界面中有`对战`或`击败`字符。
你看一下传送以后是否有`对战` `击败`的字符

**Comment by czc2912** [comment]
懂了，是因为龟舞团的任务文案里有击败。取消追踪这个任务就没问题了。感谢解惑
