### ISSUE TITLE
在无妄者副本刷取中遇到的问题

### ISSUE THREAD

**Issue by chryssss** [lazydog28/mc_auto_boss#158]
在background/task/pages/dreamless.py中，退出副本的click使用了control.click且在运行时点击失败
考虑到这个文件其他click都使用了click_position且表现正常，是否考虑改动一下该行。

顺便，在原control.click的坐标中，按照缩放为1.0来计算，如果电脑有缩放，可能原control.click的坐标需要//缩放比例？

**Comment by lazydog28** [comment]
https://github.com/lazydog28/mc_auto_boss/blob/1e56269d8b527a07ea24cfac3a881943f66f434c/background/task/pages/dreamless.py#L172

点击确定的地方坐标已经进行了缩放，理论上不应该出现点击失败的情况。

但仍采用了你的建议，修改点击方式为点击OCR识别`确认`文本的位置
