### ISSUE TITLE
有时自己打脱战了

### ISSUE THREAD

**Issue by Keyformy** [lazydog28/mc_auto_boss#16]
![QQ图片20240604020341](https://github.com/lazydog28/mc_auto_boss/assets/171552293/cde234e4-cc3d-4164-88ec-58fe73a34569)
自己脱离范围后，就一直摁着墙开火....

**Comment by lazydog28** [comment]
配置文件里面有一个最大战斗时长，当长时间处于战斗状态的时候，达到最大战斗时长会传送到下一个目标。
