### ISSUE TITLE
当前版本boss角的声骸识别率非常低，希望可以优化一下

### ISSUE THREAD

**Issue by believemiku** [lazydog28/mc_auto_boss#162]
![0320468f-3112-4929-9f6e-fd5dcc4840d7](https://github.com/lazydog28/mc_auto_boss/assets/37464565/564e8edf-e96c-433d-9d63-da806187dad8)
20次背包里就2个声骸

**Comment by lazydog28** [comment]
你这个情况属于个例不正常，我看了一下群里其他人的吸收概率没有这么低，而且哪怕不进行任何声骸识别，仅仅靠随缘吸收概率也不应该这么低

**Comment by lazydog28** [comment]
我不知道你的配置哪里有一些不正常的地方

**Comment by lazydog28** [comment]
[推荐游戏配置](https://github.com/lazydog28/mc_auto_boss/wiki/%E6%8E%A8%E8%8D%90%E6%B8%B8%E6%88%8F%E8%AE%BE%E7%BD%AE)
可以参考一下

**Comment by believemiku** [comment]
游戏设置全拉最低是好了很多
