### ISSUE TITLE
战斗结束声骸掉落后立即吸收 以及 吸收声骸时方向判定问题

### ISSUE THREAD

**Issue by ySpica** [lazydog28/mc_auto_boss#164]
战斗结束时声骸掉落，角色攻击动作未停止时同时吸收声骸，因此没有被log所纪录。

画面成功判定有声骸掉落，但是未能作出合乎预期的角色移动及转向，即使设定30秒空闲时间亦未能在时间内吸收。

⊛所有游戏设定以本项目建议设定为准

**Comment by yeming1999** [comment]
把战斗距离改成0，可以改善此情况

**Comment by ySpica** [comment]
> 把战斗距离改成0，可以改善此情况

常規及战斗距离已为0
如我所说 "所有游戏设定以本项目建议设定为准"

**Comment by yeming1999** [comment]
是的，我观察了一下，是有这个情况发生，而且跟距离无关。

1、在距离声骸4-5米的情况时，角色移动视角识别到声骸，并尝试往声骸移动；
2、在移动后，虽然声骸依旧在角色的视角范围内，但此时日志说并没有找到声骸骨；

**Comment by lyz-021187** [comment]
> 把战斗距离改成0，可以改善此情况

请问这个战斗距离在哪里改

**Comment by lazydog28** [comment]
![image](https://github.com/lazydog28/mc_auto_boss/assets/55444285/c2c1ab4c-7132-444e-8967-4cc691b58817)


> > 把战斗距离改成0，可以改善此情况
> 
> 请问这个战斗距离在哪里改

**Comment by lyz-021187** [comment]
> ![图像](https://private-user-images.githubusercontent.com/55444285/344450255-c2c1ab4c-7132-444e-8967-4cc691b58817.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3MzMzMDgsIm5iZiI6MTcxOTczMzAwOCwicGF0aCI6Ii81NTQ0NDI4NS8zNDQ0NTAyNTUtYzJjMWFiNGMtNzEzMi00NDRlLTg5NjctNGNjNjkxYjU4ODE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjMwVDA3MzY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0NWZjZDRlMzNmZDRjNzIzYmY4YmM0YzZlOGQyMTYwZmI4ZjE1NjUwZWYwNjUyYTIzMjNjY2ZkOTBhMDFhMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yz27bIwJmh85GlWXMal4mM-_dIRxuJ_7deFpoRKNdps)
> 
> > > 把战斗距离改成0，可以改善此情况
> > 
> > 
> > 请问这个战斗距离在哪里改

哦哦我以为要编辑脚本文件的 谢了
