### ISSUE TITLE
目前遇到的一些问题，关于声骸识别、月卡等

### ISSUE THREAD

**Issue by yeming1999** [lazydog28/mc_auto_boss#168]
一、声骸识别功能：
前置：将战斗距离改为0，并且视角通过鼠标轮滑拉到最近：

a. 之前版本，角色在识别到声骸后，会走几步的同时调整视角，直到走到声骸出吸收；
b. 当前版本，角色距离声骸较远，角色在第一次识别到声骸后并移动，此时角色视角中虽然有声骸，但日志却打印了没有识别到声骸的内容，并选择了传送（第一种情况）；
c. 当前版本，角色距离声骸较近，角色在第一次识别到声骸并移动，此时移动到声骸处并且画面出现了吸收，但日志打印了超过了最大空闲时间的内容，并选择了传送（第二种情况）；
![1](https://github.com/lazydog28/mc_auto_boss/assets/128339220/e5398a6c-00ea-4d92-9dea-d83b5a739361)
d. 当前版本，声骸出现在角色的面前，程序判断依旧在战斗状态中，此时吸收会不计数（第三种情况）；
![2](https://github.com/lazydog28/mc_auto_boss/assets/128339220/f70a08ad-cff5-4c8d-a887-623ee365699f)

二、月卡：
1、月卡每天晚上4点刷新，此时会一直卡在这个页面

三、背包声骸锁定：
1、在识别到主词条为攻击后，日志直接报错并退出了声骸锁定
![3](https://github.com/lazydog28/mc_auto_boss/assets/128339220/6d1eb9ec-1849-46e2-9091-c7d7efcf2bc1)

**Comment by showsorrymaker** [comment]
貌似不止攻击词条，F8整个功能都出问题了

![eb2d0aa428d3ce51f9bb0ce98eed10f2](https://github.com/lazydog28/mc_auto_boss/assets/93689264/8999ccbc-a699-4a92-9088-ee05fabb5f60)
