### ISSUE TITLE
下滑菜单有时候滑不下去

### ISSUE THREAD

**Issue by nightwishz** [lazydog28/mc_auto_boss#17]
已经调整成窗口模式，分辨率为1280x720，但是选择机械具偶的时候，在页面无法划到机械具偶在的位置，导致重复刷只在第一页能看到的声骸

**Comment by lazydog28** [comment]
游戏窗口是在屏幕的左上角嘛？

**Comment by nightwishz** [comment]
> 游戏窗口是在屏幕的左上角嘛？

下了今天更新的版本后，运行会把窗口放在左上角，已经可以下滑了，感谢！！！
