### ISSUE TITLE
角的声骸吸收问题

### ISSUE THREAD

**Issue by sinsq1986** [lazydog28/mc_auto_boss#170]
当角被击败掉落声骸恰巧就在角色眼前时吸收没问题，但绝大部分情况下角被击败掉落声骸的位置离角色较远，自动工具的powershell里提示发现声骸，角色也能自动转向，但只能往声骸方向走几步（据观察似乎只能走3~4步）的距离，此时角色距离声骸还较远，然后自动工具就离开副本了。
希望可以优化刷角副本的角色前进距离直至可以吸收。

**Comment by 18664249165** [comment]
我也是这样。估计还没空训练

**Comment by chryssss** [comment]
抛开识别率问题的话，如果是识别到了声骸但是没有吸收的话，损失是相当大的，我觉得可以接受暂时使用机械方法，也就是向前方跑一个稍微大一点的矩形来保证识别之后能吸收到？

**Comment by wyx96** [comment]
如果你只存在识别后吸收的问题的话，可以按照这样修改
<img width="1163" alt="微信图片_20240701141022" src="https://github.com/lazydog28/mc_auto_boss/assets/30570146/4a0c27c2-8929-4acf-938a-0b8880563bd4">
并且在config文件中将MaxIdleTime建议修改为20
