### ISSUE TITLE
刷角声骸有时候会卡领取奖励

### ISSUE THREAD

**Issue by gxwzjack** [lazydog28/mc_auto_boss#174]
角色移动到领取奖励的时候，会卡着，不会点离开副本，领了3次周本奖励之后还是会卡
![Image_1719804745605](https://github.com/lazydog28/mc_auto_boss/assets/174293091/bbe16386-64b4-4930-9df0-672952a76c8f)

**Comment by lazydog28** [comment]
这个界面里左面任务图标下面的离开文本怎么没有了？

**Comment by gxwzjack** [comment]
移动到那个领取奖励的附近的话，任务下面的离开文本就会变成打钩然后消失
![%3OI(DSR15CB2B(J$JZ_XP(1)](https://github.com/lazydog28/mc_auto_boss/assets/174293091/8d4b6f51-2b19-42cb-913c-99c88193cbf8)

**Comment by lazydog28** [comment]
已经更新代码，你可以更新一下试试
