### ISSUE TITLE
打完boss角之后出现的一个小bug

### ISSUE THREAD

**Issue by anxiang1123** [lazydog28/mc_auto_boss#175]
打完boss角之后经常会出现图片这种情况，然后一直重复这个界面，如果手动退出boss的关卡，那就会一直打开终端
![Snipaste_2024-07-01_17-01-10](https://github.com/lazydog28/mc_auto_boss/assets/85270032/2d163c10-7d0f-4435-89fc-d3e65d3eee74)

**Comment by biao001** [comment]
注释掉sleep函数
![image](https://github.com/lazydog28/mc_auto_boss/assets/86112787/92a43c8c-c0ed-423b-9ed8-775f9743a978)

**Comment by lazydog28** [comment]
修复了
