### ISSUE TITLE
确认离开弹窗无法点击确认

### ISSUE THREAD

**Issue by cmyyx** [lazydog28/mc_auto_boss#176]
![屏幕截图 2024-07-01 180445](https://github.com/lazydog28/mc_auto_boss/assets/140233372/c8391316-0df5-478d-a26e-0248d5faac29)

![屏幕截图 2024-07-01 160244](https://github.com/lazydog28/mc_auto_boss/assets/140233372/4b5b3853-d834-45d1-9595-40858c3d675f)

![屏幕截图 2024-07-01 145601](https://github.com/lazydog28/mc_auto_boss/assets/140233372/10865468-05fa-4da2-acc9-a0d120f5d787)

720p,1080p都试过,100%,125%,150%缩放也都试过

**Comment by chryssss** [comment]
这个问题疑似是最后一次commit产生的，退回上个版本就不会出现类似情况了

**Comment by lazydog28** [comment]
修复了，测试一下
