### ISSUE TITLE
RuntimeError: module compiled against ABI version 0x1000009 but this version of numpy is 0x2000000

### ISSUE THREAD

**Issue by yuzi910805** [lazydog28/mc_auto_boss#177]
運行之後跑出這個錯誤訊息
![螢幕擷取畫面 (1)](https://github.com/lazydog28/mc_auto_boss/assets/174374794/632a3ef9-8091-4f8e-bc57-ed03fe72465d)

**Comment by yuzi910805** [comment]
![Uploading 螢幕擷取畫面 (1).png…]()

**Comment by lazydog28** [comment]
numpy版本过高
```
pip install numpy==1.26.4
```
