### ISSUE TITLE
关于周本boss副本中吸收声骸的问题

### ISSUE THREAD

**Issue by anxiang1123** [lazydog28/mc_auto_boss#179]
现在在副本中最大空闲的停留的时间也许可以拉长一些？
我挂机的时候看了看，程序打了六次角，有三次都是发现了声骸，准备前往吸收，在前往吸收的路上显示超过了副本最大空闲时间，然后就直接执行离开的操作了
![Snipaste_2024-07-02_11-26-04](https://github.com/lazydog28/mc_auto_boss/assets/85270032/ac3c6694-b9b0-4b8b-979c-a544cd07befe)

![Snipaste_2024-07-02_11-22-10](https://github.com/lazydog28/mc_auto_boss/assets/85270032/e6136a1d-4123-474b-973c-f6b7abf740f7)

**Comment by lazydog28** [comment]
https://github.com/lazydog28/mc_auto_boss/commit/b7a10d899070cf71cea1c6445bbfe2238664c7e2

已更新
