### ISSUE TITLE
关于安装requirements中的内容时出现的错误

### ISSUE THREAD

**Issue by Bl1tzcrank** [lazydog28/mc_auto_boss#18]
![0CE75D224FF6720A7252885183216BC7](https://github.com/lazydog28/mc_auto_boss/assets/61381970/1d32fd65-920d-45d5-8351-e62f03accfaa)
开始使用官网上python3.12版本时出现了如上图的错误，找不到patch_ng包，使用pip安装后仍报相同错误。
搜了之后说是python版本过高导致，后面用了3.10的版本加上把pip下载的包的cache换了地址后就正常了。
不知道是我C盘pip缓存的目录有中文导致的还是python版本过高导致的。

**Comment by lazydog28** [comment]
按照当前的信息来说，应该是python版本过高导致。因为我之前也测试过用python3.12，也遇到了该问题。

**Comment by Bl1tzcrank** [comment]
> 按照当前的信息来说，应该是python版本过高导致。因为我之前也测试过用python3.12，也遇到了该问题。

而且貌似也不能过低，老哥里面用的一些语法好像是不兼容3.8以下的，我之前用的一直是3.7，跑出bug后才换的3.12

**Comment by lazydog28** [comment]
> > 按照当前的信息来说，应该是python版本过高导致。因为我之前也测试过用python3.12，也遇到了该问题。
> 
> 而且貌似也不能过低，老哥里面用的一些语法好像是不兼容3.8以下的，我之前用的一直是3.7，跑出bug后才换的3.12

是的，我是基于3.10开发的

**Comment by chenzf666** [comment]
3.11开始不支持patch_ng
