### ISSUE TITLE
想问一下自动重启功能的游戏路径问题

### ISSUE THREAD

**Issue by hecatekuroyuki** [lazydog28/mc_auto_boss#181]
首先想问一下自动重启功能是能正常使用吗？

自己设置如图 文件路径一定是没问题的
![image](https://github.com/lazydog28/mc_auto_boss/assets/136726333/b9c0423e-efc5-41fd-911a-758b8d9bc5e1)
但游戏崩溃后重新启动都会报错
![image](https://github.com/lazydog28/mc_auto_boss/assets/136726333/871cfdfe-1744-4858-854e-33801d0dea78)
国际服，请教一下是否有设置错误之类的

**Comment by ArcS17** [comment]
在1.06版本后可以把AppPath删掉或注释掉让程序从注册表获取安装路径，尝试一下
