### ISSUE TITLE
新版本角怎么没有等待时间了

### ISSUE THREAD

**Issue by Yunako229** [lazydog28/mc_auto_boss#182]

**Comment by lazydog28** [comment]
https://github.com/lazydog28/mc_auto_boss/blob/9e43155423b55f5790f1f2acf2656c876594b379/config.example.yaml#L7

https://github.com/lazydog28/mc_auto_boss/blob/9e43155423b55f5790f1f2acf2656c876594b379/background/task/pages/general.py#L138

已经恢复周本副本内等待时间
