### ISSUE TITLE
启动提示错误 

### ISSUE THREAD

**Issue by lan493** [lazydog28/mc_auto_boss#185]
![e104299d-7df9-45a4-ab8c-b3c77bf47e7b](https://github.com/lazydog28/mc_auto_boss/assets/31149835/c51eeb63-b705-4fae-a724-6b58c3de94d2)
环境和模型都不是装在启动盘内，启动时提示无法找到文件

**Comment by lan493** [comment]
上图原来是忘记cd了，接下来启动提示缺少module，清华源也无法下载
<img width="722" alt="微信图片_20240703142118" src="https://github.com/lazydog28/mc_auto_boss/assets/31149835/3144bcef-fb62-4883-883e-bab91d749ed2">

**Comment by lazydog28** [comment]
这个库的名字是 `pillow`
