### ISSUE TITLE
重置鼠标指针问题

### ISSUE THREAD

**Issue by xiaohun254700** [lazydog28/mc_auto_boss#19]
没有人遇到这种情况嘛？
当声骸在列表的第二页的时候，程序需要在左侧的声骸列表里面下滑然后才能让ocr识别到声骸名称。
但是程序内有一个一直重置鼠标为中心点的程序，导致鼠标不在列表滑动不了。

解决办法就是把重置鼠标中心点的代码注释掉，我看issues好像没人遇到这个问题？

为什么要加一个一直重置鼠标中心点的代码呢？是考虑什么场景呢？大佬辛苦

**Comment by lazydog28** [comment]
启动脚本后不要将鼠标放置在游戏内，也就是不要让游戏窗口获取焦点，程序在声骸列表滑动时会将鼠标位置在声骸列表的事件发送给游戏，然是如果此时你的鼠标在游戏内，那鼠标位置就会改变，导致无法正常滑动
