### ISSUE TITLE
四小时前的Commit 9e43155 中存在问题

### ISSUE THREAD

**Issue by ArcS17** [lazydog28/mc_auto_boss#190]
群友报错截图
![image](https://github.com/lazydog28/mc_auto_boss/assets/94548426/29ef19fc-34b3-472a-a436-d63ee6d8e9bb)

日志打印调用了之前版本已经删除的DreamlessWaitTime参数，将导致Attribute Error程序无法运行
![image](https://github.com/lazydog28/mc_auto_boss/assets/94548426/639594a4-ecf8-4743-b10a-6438b2872fc4)

建议删除此处logger打印，另，utils中的boss_wait函数已经实现不同周本设置不同等待时间，望参考
![image](https://github.com/lazydog28/mc_auto_boss/assets/94548426/c0552ea4-953e-495c-96eb-739a820a7384)

**Comment by lazydog28** [comment]
0fc7fa1251b649115593c97272751d5f96660c78
