### ISSUE TITLE
f6 合成声骸 依然会把符合的pass 合成声骸仍然有问题

### ISSUE THREAD

**Issue by aa911302557** [lazydog28/mc_auto_boss#191]
貌似只有电套是都能识别到  其他的比如奶套光套符合的也提示不符合
![image](https://github.com/lazydog28/mc_auto_boss/assets/57741112/4c031944-1210-4dbe-a591-8413d5f23bc5)
![image](https://github.com/lazydog28/mc_auto_boss/assets/57741112/fc757905-4ee6-4634-9954-f2429810fc82)

**Comment by RoseRin0** [comment]
# 去除非汉字字符
def remove_non_chinese(text):
    if not text:
        return False
    else:
        # 使用正则表达式匹配汉字，去除所有非汉字字符，包括括号
        result = re.sub(r'[^\u4e00-\u9fff]', '', text)
        return result

将合成和背包锁定函数中 所有ocr返回的主属性和套装属性都套用一次此函数进行去除汉字以外字符即可
我自己的文件和这边的代码差太多了 懒得pr了，有能力的自己改一下pr

**Comment by RoseRin0** [comment]
调用后的代码在 #192 覆盖现有代码即可

已由wakening pr此修复
