### ISSUE TITLE
吸收声骸时候走路一顿一顿的

### ISSUE THREAD

**Issue by oj8k** [lazydog28/mc_auto_boss#194]
https://github.com/oj8k/Wuthering-Waves/assets/37150741/870b5cf3-f1a6-4eb3-afbb-586448d01b7d

 设定如此还是我出bug了?我看到B站别人演示视频走路是正常的

**Comment by yeming1999** [comment]
B站都有跳脸的？什么逆天

**Comment by lazydog28** [comment]
用的是GPU嘛？如果是CPU运行的话，识别速度慢正常
