### ISSUE TITLE
缩放不是100%和屏幕分辨率不是1920*1080的时候有问题

### ISSUE THREAD

**Issue by Proito666** [lazydog28/mc_auto_boss#2]
例如我缩放是125%，游戏分辨率设置的1280×720，计算出来的窗口宽高是1024(1280/1.25)×567(720/1.25)导致截图不全。还有屏幕分辨率不是1920×1080的时候鼠标坐标不准

**Comment by lazydog28** [comment]
缩放设置成 100%，其他缩放我没考虑过，所以不兼容
