### ISSUE TITLE
当在背包使用声骸锁定功能是无法识别【衍射伤害加成】

### ISSUE THREAD

**Issue by user599** [lazydog28/mc_auto_boss#207]
1.  echo.config
![image](https://github.com/lazydog28/mc_auto_boss/assets/41457884/f797b0c2-5319-4891-94e2-5ef9ad31a15e)
2. 屏幕尺寸
![image](https://github.com/lazydog28/mc_auto_boss/assets/41457884/aed15abf-4a15-4b2d-9ad5-2ddd1c73d40f)

**Comment by ArcS17** [comment]
已定位问题为ocr识别“衍射”概率出错
已在 #209 fixed
