### ISSUE TITLE
无冠者需要额外进行识别处理

### ISSUE THREAD

**Issue by ZhangMDK** [lazydog28/mc_auto_boss#21]
无冠者需要额外进行识别处理，在大地图，是需要按F激活的。 直接用无妄者的脚本无法启动。

战斗结束最好能旋转一圈来识别声骇，有时候声骇出现位置在侧面，就不会去捡

**Comment by lazydog28** [comment]
在配置文件里设置好目标BOSS无冠者并设置好借位信标，刷BOSS脚本会自动激活无冠者的，而不是使用无妄者的脚本。
由于声骸识别需要使用目标识别的模型进行训练，制作训练集需要截图打标签，该过程非常枯燥，如果有愿意贡献力量的志愿者，可以联系群里的群主
