### ISSUE TITLE
请问大佬解答！

### ISSUE THREAD

**Issue by DenkiMofu** [lazydog28/mc_auto_boss#210]
这是什么情况啊大佬们  ![9ef9a1cb-d44c-401b-b276-c7591547e8ef](https://github.com/lazydog28/mc_auto_boss/assets/174820580/aba4e2e6-a9a6-484e-892d-f770ee6fd6a1)

**Comment by lazydog28** [comment]
没装依赖
```
pip install requests
```

**Comment by DenkiMofu** [comment]
感谢大佬解决了！但又有一个问题随之而来
![111](https://github.com/lazydog28/mc_auto_boss/assets/174820580/5ad307bb-4695-4fdc-8691-301cebffdecb)

**Comment by lazydog28** [comment]
应该是缺少东西了，是按照下面的搭建流程走的吗？
[GPU环境搭建](https://github.com/lazydog28/mc_auto_boss/wiki/GPU%E7%8E%AF%E5%A2%83%E6%90%AD%E5%BB%BA)

**Comment by DenkiMofu** [comment]
是的，但到了安装paddlepaddle-gpu环节会出现如图情况，所以我自己到官方下载安装了CUDA 11.7，cuDNN v8.4.1
![22](https://github.com/lazydog28/mc_auto_boss/assets/174820580/8c04b5af-530f-41c2-b622-65df20d3b0d6)
