### ISSUE TITLE
程序运行时所占内存越来越大

### ISSUE THREAD

**Issue by OvO894** [lazydog28/mc_auto_boss#212]
<img width="1534" alt="屏幕截图 2024-07-06 050144" src="https://github.com/lazydog28/mc_auto_boss/assets/174693871/e83fd57f-6355-4b92-8bde-555259313d2b">
运行130次，电脑32G物理内存和48G虚拟内存就快吃满了
能不能加一下定期清理内存的功能

**Comment by lazydog28** [comment]
清理内存可以自行安装清理内存的插件比如`Men Reduct`
