### ISSUE TITLE
一角脚就这样刷别的boss不会

### ISSUE THREAD

**Issue by LYIFIDI** [lazydog28/mc_auto_boss#216]
![9fa7b613469fb76b4b1778655403eb80](https://github.com/lazydog28/mc_auto_boss/assets/162010125/c1aac14f-039e-4aed-9e68-3a59f4c5a4f5)
![b934757692ded6e6655f5fd4fca71b22](https://github.com/lazydog28/mc_auto_boss/assets/162010125/8af33b09-83cb-439c-a0a4-9e2ce3abae8a)

**Comment by lazydog28** [comment]
配置文件截图发一下

**Comment by LYIFIDI** [comment]
![222](https://github.com/lazydog28/mc_auto_boss/assets/162010125/abf0f108-2ae7-46b4-8d45-fa7959252628)

**Comment by LYIFIDI** [comment]
这样子他会跳过角，只留角就会报错

**Comment by RoseRin0** [comment]
> 这样子他会跳过角，只留角就会报错

有没有一种可能
`- "BOSS名字"`
你要注释的话只能在-的前面注释？
`# - "BOSS名字”`
而不是
`- # “BOSS名字”`
