### ISSUE TITLE
更新后报错

### ISSUE THREAD

**Issue by qxw010** [lazydog28/mc_auto_boss#217]
![847202F9F569242EAC65A89B94B9CB58](https://github.com/lazydog28/mc_auto_boss/assets/174119198/3ef98c3c-7fa1-49dd-87c0-62b7cfd820b2)

**Comment by lazydog28** [comment]
配置文件截图发一下

**Comment by qxw010** [comment]
![Uploading image.png…]()

**Comment by qxw010** [comment]
![Uploading Snipaste_2024-07-06_12-27-34.png…]()

**Comment by qxw010** [comment]
可以用了，删错东西了
