### ISSUE TITLE
卡加载问题

### ISSUE THREAD

**Issue by wakening** [lazydog28/mc_auto_boss#220]
@wang115t @lazydog28 游戏卡加载已在pr[#203]commit[6bc9289e436145543054f2675df4402a302b1a20] 实现定时文字识别右下角的加载值，长时间（3min）进度没动则关闭游戏进程， 我看pr[#215]增加了类似的功能，而且使用的是图片两两匹配相似度实现，isLoad文件夹存放了十数张大图，仍无法覆盖所有进度值，光进度条就有0-100，背景也有很多种，这样实现不太合理，是否合并这两个功能

**Comment by RoseRin0** [comment]
解决方法：加载中持续找几个点的颜色，如果持续x分钟，这几个点的颜色都没有变化(每次找色与上次找色的对比阈值0.9左右)，那么判定为卡加载了，重启游戏。
已有找色函数：contrast_colors

不需要指定颜色，只需要获取指定坐标颜色，然后每次与其对比。目前加载时背景图片是不会变化的，所以不管背景和进度条怎么变，只要没有进副本或者退出副本，那么这几个点的颜色就不会变，一旦加载完毕 那么颜色变化就能判断出是否加载完毕。

**Comment by RoseRin0** [comment]
要硬识别的话也不是不行，用现有ocr识别"%"的指定区域即可

代码如下：
```
def check_loading():
    region = set_region(1735, 970, 1845, 1020)
    loading_progress = "0%"
    while loading_progress != "100%" and check_in_animation() != "is available":
        text_result = wait_text_designated_area("%", 1, region, 3, full_text_return=True)
        loading_progress = text_result[0].text
        logger(f"当前加载：{loading_progress}")
        time.sleep(0.2)
```
然后在每个传送或者退出副本的地方调用这个函数即可，能正常识别百分比。
百分比一直没动就调用重启函数啥的。

（check_in_animation()是我自用版本里的一个识别当前角色是否可操作的函数，可以去掉，也可以想想怎么实现它。）

函数调用效果：
```
【INFO】战斗次数：0 吸收次数：0 治疗次数：0 分辨率正确，使用适配坐标
【INFO】战斗次数：0 吸收次数：0 治疗次数：0 当前目标boss：无妄者
【INFO】战斗次数：0 吸收次数：0 治疗次数：0 等待传送完成
【INFO】战斗次数：0 吸收次数：0 治疗次数：0 当前加载：32%
【INFO】战斗次数：0 吸收次数：0 治疗次数：0 当前加载：46%
【INFO】战斗次数：0 吸收次数：0 治疗次数：0 当前加载：61%
【INFO】战斗次数：0 吸收次数：0 治疗次数：0 当前加载：75%
【INFO】 战斗次数：0 吸收次数：0 治疗次数：0 当前加载：90%
【INFO】 战斗次数：0 吸收次数：0 治疗次数：0 当前加载：100%
【INFO】 战斗次数：0 吸收次数：0 治疗次数：0 传送完成
```
