### ISSUE TITLE
建议加一个BOSS循环间隔中回城补血的选项

### ISSUE THREAD

**Issue by 3055909481** [lazydog28/mc_auto_boss#24]
循环几次后可能出现奶不起来主C挂了的情况

**Comment by nosilence1994** [comment]
可以在残像探寻里探测“朔雷之鳞”，它右边有个信标，位置是固定的
```python
def transfer_health():
    logger_msg("回信标恢复状态")
    control.activate()
    control.tap(win32con.VK_F2)
    if not wait_text(["日志", "活跃度", "周期挑战", "强者之路", "残象"]):
        logger_msg("未进入索拉指南")
        control.esc()
        return False
    time.sleep(1)
    control.click(75 * width_ratio, 720 * height_ratio)
    if not wait_text("探测"):
        logger_msg("未进入残像探寻")
        control.esc()
        return False
    bossName = "朔雷之鳞"
    findBoss = None
    for i in range(20):
        findBoss = find_text(bossName)
        if findBoss:
            break
        control.scroll(-20, 500 * width_ratio, 500 * height_ratio)
        time.sleep(0.3)
    if not findBoss:
        control.esc()
        logger_msg("未找到目标boss")
        return False
    click_position(findBoss.get("position"))
    click_position(findBoss.get("position"))
    time.sleep(1)
    control.click(1700 * width_ratio, 980 * height_ratio)
    if not wait_text("追踪"):
        control.esc()
        return False
    time.sleep(1)
    control.click(1160 * width_ratio, 520 * height_ratio)
    time.sleep(2)
    control.click(1600 * width_ratio, 1010 * height_ratio)
    time.sleep(10)
    return True
```

**Comment by lazydog28** [comment]
> 可以在残像探寻里探测“朔雷之鳞”，它右边有个信标，位置是固定的
> 
> ```python
> def transfer_health():
>     logger_msg("回信标恢复状态")
>     control.activate()
>     control.tap(win32con.VK_F2)
>     if not wait_text(["日志", "活跃度", "周期挑战", "强者之路", "残象"]):
>         logger_msg("未进入索拉指南")
>         control.esc()
>         return False
>     time.sleep(1)
>     control.click(75 * width_ratio, 720 * height_ratio)
>     if not wait_text("探测"):
>         logger_msg("未进入残像探寻")
>         control.esc()
>         return False
>     bossName = "朔雷之鳞"
>     findBoss = None
>     for i in range(20):
>         findBoss = find_text(bossName)
>         if findBoss:
>             break
>         control.scroll(-20, 500 * width_ratio, 500 * height_ratio)
>         time.sleep(0.3)
>     if not findBoss:
>         control.esc()
>         logger_msg("未找到目标boss")
>         return False
>     click_position(findBoss.get("position"))
>     click_position(findBoss.get("position"))
>     time.sleep(1)
>     control.click(1700 * width_ratio, 980 * height_ratio)
>     if not wait_text("追踪"):
>         control.esc()
>         return False
>     time.sleep(1)
>     control.click(1160 * width_ratio, 520 * height_ratio)
>     time.sleep(2)
>     control.click(1600 * width_ratio, 1010 * height_ratio)
>     time.sleep(10)
>     return True
> ```

好主意，等我先把其他的改改再考虑这个
