### ISSUE TITLE
更新后报错

### ISSUE THREAD

**Issue by lyz-021187** [lazydog28/mc_auto_boss#243]
![Uploading 鸣潮   2024_7_9 21_20_37.png…]()

**Comment by lyz-021187** [comment]
![鸣潮   2024_7_9 21_20_37](https://github.com/lazydog28/mc_auto_boss/assets/173454869/c1aa2463-e248-4f3d-95b6-4dff14e62ab2)

**Comment by lazydog28** [comment]
截图没有正常上传

**Comment by lazydog28** [comment]
有报错请先自行百度
```
pip install pyautogui
```
