### ISSUE TITLE
无妄者和角可以支持吗

### ISSUE THREAD

**Issue by llby1213** [lazydog28/mc_auto_boss#244]
他好像不会自己进入副本里打无妄者和角，地图上选定就会死机
![7e17dc91ec31f98896a5a28e50a663dc](https://github.com/lazydog28/mc_auto_boss/assets/175191073/84e73c2e-3877-481f-9759-fa0f35f8ce74)

**Comment by lazydog28** [comment]
已经支持，无妄者直接设置目标BOSS为无妄者，角的话在入口放借位信标

**Comment by llby1213** [comment]
![337bc1b3848c5b967ab612552273f72d](https://github.com/lazydog28/mc_auto_boss/assets/175191073/956153c0-2a0c-471c-8ddf-7d719a1a9248)
角传送过去不进副本然后就找下一个boss去了

**Comment by llby1213** [comment]
![34933c35b8add88edaa6a46bcc27edb0](https://github.com/lazydog28/mc_auto_boss/assets/175191073/bf99792b-becc-4a8c-9bb6-26d985895bf8)
我再门口放的信标

**Comment by lazydog28** [comment]
传送过去以后会检测`进入`字符，你这可能是没检测到

**Comment by lazydog28** [comment]
另外截图的时候把时间也要截取上，不然没法判断原因

**Comment by llby1213** [comment]
龟龟就是传送过去就会进入战斗，无妄者他好像不会传送卡在哪里，角就正常传送过去然后也不会进入

**Comment by llby1213** [comment]
![c56bc0b47840b2910bdfe4399900bd6c](https://github.com/lazydog28/mc_auto_boss/assets/175191073/c12263d9-dae1-4b1d-98f8-174642ee2486)
