### ISSUE TITLE
运行..\mc_auto_boss-gpu\background\main.py的时候的报错问题

### ISSUE THREAD

**Issue by Lexce-create** [lazydog28/mc_auto_boss#247]
![图片](https://github.com/lazydog28/mc_auto_boss/assets/131461266/a0612e32-97d8-4e42-9fa6-ca2d09168920)
在安装了pillow的情况下仍然报错找不到该动态链
![图片](https://github.com/lazydog28/mc_auto_boss/assets/131461266/279873ef-c46c-4b62-a355-50a028d58e13)

**Comment by ArcS17** [comment]
请自行检查依赖安装过程
