### ISSUE TITLE
单个角色阵亡后-建议先进入激活点复活

### ISSUE THREAD

**Issue by wang115t** [lazydog28/mc_auto_boss#25]
单个角色阵亡后-建议先进入激活点复活

**Comment by RoseRin0** [comment]
> 单个角色阵亡后-建议先进入激活点复活

#88   简单写了个，能用就行

**Comment by wakening** [comment]
> > 死亡后建议死亡点
> 
> #88 简单写了个，能用就行

建议将复活改为被动触发，即在战斗中若检测到复活弹窗就记录下，在打下一个boss前去一次复活点，现在的复活检测有点磨叽

**Comment by RoseRin0** [comment]
> > > 死亡后建议死亡点
> > 
> > 
> > #88 简单写了个，能用就行
> 
> 建议将复活改为被动触发，即在战斗中若检测到复活弹窗就记录下，在打下一个boss前去一次复活点，现在的复活检测有点磨叽

不考虑，战斗中连续截图识图会导致连招不流畅

**Comment by wakening** [comment]
> > > > 死亡后建议死亡点
> > > 
> > > 
> > > #88 简单写了个，能用就行
> > 
> > 
> > 建议将复活改为被动触发，即在战斗中若检测到复活弹窗就记录下，在打下一个boss前去一次复活点，现在的复活检测有点磨叽
> 
> 不考虑，战斗中连续截图识图会导致连招不流畅

目前刷3个世界boss时的逻辑是仅启动时会主动切人检测是否阵亡，后续战斗不会再主动检测，这个没问题，问题在于单刷无妄者时，每次战斗开始前都会切人检测是否阵亡，过于耗时，这里应像刷世界boss时那样，非首次就不检测了，此处应仅是逻辑上的改动，不涉及额外增加ocr

**Comment by RoseRin0** [comment]
1.世界BOSS也会在打完，检测完声骸后进行切人识别。
2.Config中可以关闭复活功能。

**Comment by wakening** [comment]
> 1.世界BOSS也会在打完，检测完声骸后进行切人识别。 2.Config中可以关闭复活功能。

实测打世界boss战斗结束后不会检测，一直显示无需治疗（即便有角色阵亡了），我在世界等级5，不开启搜索声骸，不带奶妈进行的测试，这或许是个bug？

**Comment by RoseRin0** [comment]
> > 1.世界BOSS也会在打完，检测完声骸后进行切人识别。 2.Config中可以关闭复活功能。
> 
> 实测打世界boss战斗结束后不会检测，一直显示无需治疗（即便有角色阵亡了），我在世界等级5，不开启搜索声骸，不带奶妈进行的测试，这或许是个bug？

开始第一次以及搜索声骸后才会实行此代码，并非BUG。
