### ISSUE TITLE
云闪之鳞的声骸识别有问题，老是识别不到

### ISSUE THREAD

**Issue by HugoLau91** [lazydog28/mc_auto_boss#253]
并非偶发事件，miss率粗略计算达到1/2，建议加强识别强度/参数等。
![QQ截图20240712020254](https://github.com/lazydog28/mc_auto_boss/assets/148528479/196365b7-f04a-472f-9aea-d879bdfdd0a8)

**Comment by lazydog28** [comment]
#171

**Comment by lazydog28** [comment]
[游戏推荐设置](https://github.com/lazydog28/mc_auto_boss/wiki/%E6%8E%A8%E8%8D%90%E6%B8%B8%E6%88%8F%E8%AE%BE%E7%BD%AE)
