### ISSUE TITLE
索拉指南追踪问题

### ISSUE THREAD

**Issue by KokonaShiki** [lazydog28/mc_auto_boss#261]
![348443833-052698b2-0d2b-4a75-a88a-4a570100a390](https://github.com/user-attachments/assets/882b4222-a829-4288-8edc-87b7ec7cba01)
如果运行main.py时人物不在副本门口，脚本会无限执行寻找boss的操作，在索拉指南的角boss页面不会自动点击探测而是直接退出指南页面并重复寻找，并发出日志【WARN】 2024-07-13 10:22:41 战斗次数：1 吸收次数：1 治疗次数：0 未找到追踪
运行环境：
i5 10400f + RX 6700XT
软件环境python版本3.12.0，使用anaconda，以及cpu版本的飞桨pip安装，其他与readme无异

**Comment by ArcS17** [comment]
可以将出现此情况时完整的mc_log上传帮助定位问题

**Comment by KokonaShiki** [comment]
[mc_log_摩托.txt](https://github.com/user-attachments/files/16202029/mc_log_.txt)
[mc_log_角.txt](https://github.com/user-attachments/files/16202030/mc_log_.txt)

**Comment by ArcS17** [comment]
> [mc_log_摩托.txt](https://github.com/user-attachments/files/16202029/mc_log_.txt) [mc_log_角.txt](https://github.com/user-attachments/files/16202030/mc_log_.txt)

可以尝试将分辨率调整为1080p 屏幕缩放1.0或720p 屏幕缩放1.5

**Comment by KokonaShiki** [comment]
我试着修改代码，我在template中放置了![image](https://github.com/user-attachments/assets/1bebc69f-94d8-42f8-9a09-5a94e2c28f6c)图片，并将utils.py中在310行的 `random_click(1700, 1025)` 修改成了如下代码
```
coordinate_1 = find_pic(template_name=f"button_discover.png", threshold=0.55)
    if not coordinate_1:
        logger("识别探测按钮失败", "WARN")
        control.esc()
        return False
    click_position(coordinate_1)  # 进入地图寻找boss位置
```
修改后可以实现点击探测按钮，后续在点击屏幕中心时，我尝试通过图片识别实现，但效果不好，后续使用
```
    position1 = Position
    position1.x1 = 960
    position1.x2 = 960
    position1.y1 = 540
    position1.y2 = 540
    click_position(position1)
    logger("clicked", "INFO")
```
进行点击屏幕中心，实测可以实现点击操作，后续脚本运行一切正常，事实上，点击探测按钮也可以使用定义Position的变量实现，但后者代码不太优雅(

猜测可能是randomclick函数会受到不明原因影响导致点击位置有偏差（比如系统显示缩放大小？），使用clickposition函数似乎可以避免这一类问题，
我解决该问题的思路如上，希望能给作者以参考

**Comment by ArcS17** [comment]
random_click是以原生1080p分辨率为基准乘以实际窗口缩放比例进行点击位置确定，template所截取的图片也是在特定分辨率下所获得，所以主要适配16:9特定分辨率下的游戏窗口并作出了使用提醒，如果模拟点击也使用find_pic进行图像识别会比较影响脚本性能，当然能自行修改代码满足特定使用条件的需求并分享是很值肯定的的。

**Comment by ArcS17** [comment]
> 我试着修改代码，我在template中放置了![image](https://private-user-images.githubusercontent.com/143982196/348476107-1bebc69f-94d8-42f8-9a09-5a94e2c28f6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4ODE1NjksIm5iZiI6MTcyMDg4MTI2OSwicGF0aCI6Ii8xNDM5ODIxOTYvMzQ4NDc2MTA3LTFiZWJjNjlmLTk0ZDgtNDJmOC05YTA5LTVhOTRlMmMyOGY2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxM1QxNDM0MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YWY5ZTkyZGU2MzAzMGVmYWZmODk4MTY0NzljMTI1MTRlMTIwZjEwOTY4ZDE5ZTMxMzRlOGI0ODUwOTRjMTQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oKR_6N8aXSKAuISqAWn4N21mXtPjqk5aHPkjBAadZM8)图片，并将utils.py中在310行的 `random_click(1700, 1025)` 修改成了如下代码
> 
> ```
> coordinate_1 = find_pic(template_name=f"button_discover.png", threshold=0.55)
>     if not coordinate_1:
>         logger("识别探测按钮失败", "WARN")
>         control.esc()
>         return False
>     click_position(coordinate_1)  # 进入地图寻找boss位置
> ```
> 
> 修改后可以实现点击探测按钮，后续在点击屏幕中心时，我尝试通过图片识别实现，但效果不好，后续使用
> 
> ```
>     position1 = Position
>     position1.x1 = 960
>     position1.x2 = 960
>     position1.y1 = 540
>     position1.y2 = 540
>     click_position(position1)
>     logger("clicked", "INFO")
> ```
> 
> 进行点击屏幕中心，实测可以实现点击操作，后续脚本运行一切正常，事实上，点击探测按钮也可以使用定义Position的变量实现，但后者代码不太优雅(
> 
> 猜测可能是randomclick函数会受到不明原因影响导致点击位置有偏差（比如系统显示缩放大小？），使用clickposition函数似乎可以避免这一类问题， 我解决该问题的思路如上，希望能给作者以参考

random_click是以原生1080p分辨率为基准乘以实际窗口缩放比例进行点击位置确定，template所截取的图片也是在特定分辨率下所获得，所以主要适配16:9特定分辨率下的游戏窗口并作出了使用提醒，如果模拟点击也使用find_pic进行图像识别会比较影响脚本性能，当然能自行修改代码满足特定使用条件的需求并分享是很值肯定的的。
