### ISSUE TITLE
求支持2k 125%缩放

### ISSUE THREAD

**Issue by will-911** [lazydog28/mc_auto_boss#266]
目前显示器是2k，日常使用125%缩放，使用的时候需要切换成100才行，求大佬支持

**Comment by lazydog28** [comment]
理论上125%缩放应该能正常运行
截图脚本运行初始化时显示的屏幕缩放我看一下

https://github.com/lazydog28/mc_auto_boss/blob/390dfafb2ae049ea3f438091c2c3ca4c1d27312c/background/init.py#L31

**Comment by will-911** [comment]
我的问题，更新了之后，测试没问题，大佬nb！！
