### ISSUE TITLE
大佬，为啥我没有mc_auto_boss

### ISSUE THREAD

**Issue by ASDASDAED123131** [lazydog28/mc_auto_boss#268]
![66f1bc6123e9bce8ee06e1f498005ef](https://github.com/user-attachments/assets/c6f416be-5275-4326-bc80-4093c12c482f)

**Comment by RoseRin0** [comment]
有没有一种可能 这个项目的名称就叫做mc_auto_boss，你需要在Code页面下载zip解压，或者使用git进行拉取。

**Comment by yeming1999** [comment]
点击网页的 mc_auto_boss->点击<>COde ->点击download ZIP  解压后就是mc_auto_boss
之后根据网页教程安装依赖
建议还是配合对话AI安装依赖，比如讯飞星火，安装时大概率会有报错

**Comment by ASDASDAED123131** [comment]
> 点击网页的 mc_auto_boss->点击<>COde ->点击download ZIP 解压后就是mc_auto_boss 之后根据网页教程安装依赖 建议还是配合对话AI安装依赖，比如讯飞星火，安装时大概率会有报错

谢谢大佬
