### ISSUE TITLE
请在config.yaml中填写目标BOSS全名

### ISSUE THREAD

**Issue by gyx-0** [lazydog28/mc_auto_boss#27]
我下载安装好后，更改了boss只有鸣钟之龟，在cmd运行报“请在config.yaml中填写目标BOSS全名”，但是boss名字就是鸣钟之龟啊。
![屏幕截图 2024-06-05 151225](https://github.com/lazydog28/mc_auto_boss/assets/82511104/9afb226e-5544-4ad7-92f7-d32cb19eea6c)

**Comment by lazydog28** [comment]
config.yaml 该配置文件应该在根目录或者你命令行运行目录

**Comment by gyx-0** [comment]
![目录](https://github.com/lazydog28/mc_auto_boss/assets/82511104/50d27d7a-7e89-4dd6-a104-d6d8cf66083a)
我的yaml文件在这个位置，是放错位置了吗

**Comment by gyx-0** [comment]
![config](https://github.com/lazydog28/mc_auto_boss/assets/82511104/35cffab5-166d-4dc8-bbf0-6908ff2989e9)
![输出](https://github.com/lazydog28/mc_auto_boss/assets/82511104/c61e2cda-7337-4736-b738-56c0274313c0)
我试着测试了一下，程序好像是能读到yaml文件，但不能读取，但我是在powershell管理员权限下运行的，应该不会存在权限不足的问题

**Comment by lazydog28** [comment]
放的位置没错，但是你命令行的工作目录是在哪？

**Comment by gyx-0** [comment]
我在system32下添加了新的config.yaml文件问题解决了，谢谢dalao指点

**Comment by lazydog28** [comment]
按照常理里说，你应该在命令行使用cd命令，进入项目目录再运行代码
