### ISSUE TITLE
1

### ISSUE THREAD

**Issue by 1123348400** [lazydog28/mc_auto_boss#28]
![Image_1717571269849](https://github.com/lazydog28/mc_auto_boss/assets/171772785/b2780c4e-7b66-4c91-8db9-45a1f8a2606d)
为什么启动之后就没有然后了

**Comment by lazydog28** [comment]
你的python命令应该是被windows内置的python安装器占用了，你需要指定python的绝对路径来运行脚本

**Comment by 1123348400** [comment]
照着ai弄了半天还是没处理掉问题，应该怎么操作啊佬

**Comment by lazydog28** [comment]
实在搞不定就用一键启动的脚本

**Comment by lazydog28** [comment]
windows键盘+R键 调出运行窗口，然后输入cmd，启动cmd命令行
`cd "%USERPROFILE%\AppData\Local\Microsoft\WindowsApps"`

`del /f /q python.exe`

输入上述两条命令
