### ISSUE TITLE
一点错误和建议

### ISSUE THREAD

**Issue by CodeMagic6** [lazydog28/mc_auto_boss#283]
1，角色装备了燎照之骑时，程序使用声骸时，会骑摩托跑出副本，建议代码改成短按Q，而不是长按。
2，其次，声骸吸收后，程序不会领取奖励，而是原地呆住，不能继续下一个轮回，建议增加领取奖励。
3，最后，角色该做什么，可以联合视觉GPU，探测到画面，判断下一步逻辑，而不是逐步执行代码。

**Comment by yeming1999** [comment]
"摩托车短按请用q~0.1"
这个有在配置文件中说明，摩托是 q~0.1,q~0.1,q~0.1

**Comment by ArcS17** [comment]
不知所谓，建议close
