### ISSUE TITLE
为什么运行的时候总是容易卡在探测界面不动了呢

### ISSUE THREAD

**Issue by kunhuang12345** [lazydog28/mc_auto_boss#284]

**Comment by lazydog28** [comment]
请提供截图

**Comment by yeming1999** [comment]
你是不是运行的时候鼠标放在游戏中了，需要切出去

**Comment by kunhuang12345** [comment]
> 你是不是运行的时候鼠标放在游戏中了，需要切出去

没有，我将鼠标放在终端内，我再运行一次截图发一下

**Comment by kunhuang12345** [comment]
> 你是不是运行的时候鼠标放在游戏中了，需要切出去

嗯嗯，好的

**Comment by kunhuang12345** [comment]
> 请提供截图
![image](https://github.com/user-attachments/assets/c06ee5fa-9d47-4408-a29f-789eeebf684d)
你看，时间在18：34的时候就卡住了，很奇怪

**Comment by ArcS17** [comment]
提issue起码更新到当前版本吧

**Comment by kunhuang12345** [comment]
> 提issue起码更新到当前版本吧

咦，release的原来不是最新版本吗

**Comment by ArcS17** [comment]
> > 提issue起码更新到当前版本吧
> 
> 咦，release的原来不是最新版本吗

大概落后80个pr吧

**Comment by kunhuang12345** [comment]
> > > 提issue起码更新到当前版本吧
> > 
> > 
> > 咦，release的原来不是最新版本吗
> 
> 大概落后80个pr吧

可以了，谢谢
