### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by mxyooR** [lazydog28/mc_auto_boss#290]
![image](https://github.com/user-attachments/assets/821659bb-9c4c-430b-b7f5-bbe02c90c883)显卡为4060，已重装requirements过

**Comment by lazydog28** [comment]
没装cuda    [GPU环境搭建](https://github.com/lazydog28/mc_auto_boss/wiki/GPU%E7%8E%AF%E5%A2%83%E6%90%AD%E5%BB%BA)
