### ISSUE TITLE
刷boss不能循环刷多个boss

### ISSUE THREAD

**Issue by dadalia11** [lazydog28/mc_auto_boss#295]
如题，自动刷4c只会刷单独一只声骸，用的配置文档是下载下来的默认文档，比如刷角就只会单独刷角

**Comment by lazydog28** [comment]
配置文件里可以配置多个目标，目标BOSS的位置是有借位信标的，可以少字但是不能有错别字

https://github.com/lazydog28/mc_auto_boss/blob/gpu/config.example.yaml
