### ISSUE TITLE
直装版报错

### ISSUE THREAD

**Issue by Bowen9292** [lazydog28/mc_auto_boss#297]
RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:857 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasnt able to be loaded. Please install the correct version of CUDA andcuDNN as mentioned in the GPU requirements page  (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements),  make sure they're in the PATH, and that your GPU is supported.

**Comment by Bowen9292** [comment]
是我cuda没装对吗

**Comment by sykuu5414** [comment]
我也遇到同样问题，应该是CUDA版本太低原因（10系显卡用的10.2）。后来转用cpu了

**Comment by sykuu5414** [comment]
运行用的onnxruntime版本对CUDA版本有要求，尝试降了onnxruntime版本匹配CUDA又出现与其他包的兼容问题，老显卡CUDA版本上限受限升不了就索性直接改用cpu了

**Comment by Bowen9292** [comment]
cpu是不是更方便 我试试

**Comment by Bowen9292** [comment]
用直装版了

**Comment by Bowen9292** [comment]
用CPU直装版了
