### ISSUE TITLE
py3.8.10的版本 不知道这是哪里出现了问题

### ISSUE THREAD

**Issue by PierceLiu** [lazydog28/mc_auto_boss#3]
![image](https://github.com/lazydog28/mc_auto_boss/assets/57214772/e1bfd757-105d-4e51-86ae-284d800b5dda)

**Comment by Proito666** [comment]
config.yaml要设置下TargetBoss，参考[https://github.com/lazydog28/mc_auto_boss/blob/master/config.example.yaml](config.example.yaml)

**Comment by PierceLiu** [comment]
收到。等回复吧。

**Comment by PierceLiu** [comment]
![image](https://github.com/lazydog28/mc_auto_boss/assets/57214772/c16fad59-4283-4dcb-bdd6-af0e3b4f318d)
nin
您好，我已经确认是添加了目标，但是还是没有成功，麻烦您看一下是怎么个情况呗~

**Comment by lazydog28** [comment]
![image](https://github.com/lazydog28/mc_auto_boss/assets/55444285/d1ea0fb1-9c6c-40d2-a693-6d0c5aff9328)

**Comment by PierceLiu** [comment]
> config.yaml要设置下TargetBoss，参考[config.example.yaml](https://github.com/lazydog28/mc_auto_boss/blob/master/config.example.yaml)

依旧没有成功，可以讲您的config.yaml截个图参考下么

**Comment by lazydog28** [comment]
> > config.yaml要设置下TargetBoss，参考[config.example.yaml](https://github.com/lazydog28/mc_auto_boss/blob/master/config.example.yaml)
> 
> 依旧没有成功，可以讲您的config.yaml截个图参考下么

示例配置文件就是一个完整的配置文件，不修改就能运行，只不过不修改的话，刷的就是鸣钟之龟 燎照之骑 聚械机偶

**Comment by lazydog28** [comment]
> > config.yaml要设置下TargetBoss，参考[config.example.yaml](https://github.com/lazydog28/mc_auto_boss/blob/master/config.example.yaml)
> 
> 依旧没有成功，可以讲您的config.yaml截个图参考下么

你可以先去学习一下 yaml
