### ISSUE TITLE
正常运行超过一段时间就会出现反复定位但不传送的现象

### ISSUE THREAD

**Issue by Yunako229** [lazydog28/mc_auto_boss#30]
![{C8BB88F1-CEB1-45ea-9DA1-92CD28F260A2}](https://github.com/lazydog28/mc_auto_boss/assets/84826080/2a949afe-c5ab-48b9-be47-84323c2aef9e)
![{2B8387BF-6868-4c2d-B613-E9A27EEBCB03}](https://github.com/lazydog28/mc_auto_boss/assets/84826080/989c0624-f555-4b7b-9afe-ad2482d10422)

**Comment by lazydog28** [comment]
这个问题没有遇到过，而且很难复现，没法定位原因，怀疑是发送按下F2事件给游戏窗口未成功发送
