### ISSUE TITLE
战斗后不进入循环，到了这个页面之后不进行传送

### ISSUE THREAD

**Issue by tianming0715** [lazydog28/mc_auto_boss#32]
战斗后不进入循环，到了这个页面之后不进行传送，借位信标已经放置
![Uploading QQ图片20240606115553.png…]()

**Comment by tianming0715** [comment]
![Uploading QQ图片20240606115553.png…]()

**Comment by lazydog28** [comment]
你的图片我这边加载不出来，你可以更新一下最新代码再测试一下。我怀疑是OCR识别速度过慢的问题

**Comment by tianming0715** [comment]
已经解决了，谢谢大佬
