### ISSUE TITLE
一直显示未进入索拉指南是怎么回事

### ISSUE THREAD

**Issue by yanagisann0306** [lazydog28/mc_auto_boss#37]
脚本一直显示未进入索拉指南 没有自动打开怪的那一页

**Comment by lazydog28** [comment]
https://github.com/lazydog28/mc_auto_boss/blob/544687ab2c17ea04d58a36bf73ae47df907c9f01/background/utils.py#L218

脚本判断是否进入索拉指南是根据OCR识别结果来判断，`["日志", "活跃度", "周期挑战", "强者之路", "残象"] `OCR结果中匹配其中任意文字则认为进入成功。我不知道你的索拉指南是什么状态
