### ISSUE TITLE
探寻部分出错

### ISSUE THREAD

**Issue by 1714775263** [lazydog28/mc_auto_boss#4]
![QQ截图20240602191726](https://github.com/lazydog28/mc_auto_boss/assets/45120294/15f5ce06-81cf-4243-9fc2-e97b4e106272)
开始刷boss会点击最后一个。
![QQ截图20240602191820](https://github.com/lazydog28/mc_auto_boss/assets/45120294/bdff2dde-e6f4-47a5-91ae-6641e7fb3cc7)

这里的导致没有点击那个残像探寻。
分辨率都测试过了。暂时不清楚啥原因

**Comment by lazydog28** [comment]
你屏幕分辨率是多少的？

**Comment by frg666** [comment]
> 你屏幕分辨率是多少的？

我也有相同的问题，我是1920*1080，游戏分辨率设置为1280x720，缩放100%

**Comment by frg666** [comment]
带摩托声骸角色会骑着摩托跑掉

**Comment by lazydog28** [comment]
警觉，我的漂泊日志和残象探寻位置和你不一样
![image](https://github.com/lazydog28/mc_auto_boss/assets/55444285/e4a57f98-43e3-436a-8274-2a00feab817e)

**Comment by lazydog28** [comment]
等我去改成图片匹配，待会你更新一下代码再试试

**Comment by 1714775263** [comment]
> > 带摩托声骸角色会骑着摩托跑掉
> 
> 不影响，战斗超时会进行下一个目标

好的

**Comment by lazydog28** [comment]
更新了，你更新一下代码再试试

**Comment by lazydog28** [comment]
> > 你屏幕分辨率是多少的？
> 
> 我也有相同的问题，我是1920*1080，游戏分辨率设置为1280x720，缩放100%


更新了，你更新一下代码再试试

**Comment by frg666** [comment]
> > > 你屏幕分辨率是多少的？
> > 
> > 
> > 我也有相同的问题，我是1920*1080，游戏分辨率设置为1280x720，缩放100%
> 
> 更新了，你更新一下代码再试试

ok,我试一下
