### ISSUE TITLE
200%缩放下无法使用

### ISSUE THREAD

**Issue by DBY2-W00** [lazydog28/mc_auto_boss#40]
100%缩放的时候是能用的，但是字太小了
看了看虽然游戏里设成了1280x720，但是缩放后变成1280x888了，不知道是怎么回事
是哪里设置错了吗？

![屏幕截图 2024-06-06 165248](https://github.com/lazydog28/mc_auto_boss/assets/16357305/d8cd0c02-974b-46e1-a646-7ad9189c37d8)

**Comment by lazydog28** [comment]
我的电脑分辨率不足，没办法测试200%的缩放，所以没法定位问题

**Comment by lazydog28** [comment]
你可以测试一下其他你能接受的分辨率

**Comment by oUp2Uo** [comment]
您好请问这个放大的时候不能用大概是什么原因呢，能不能通过手动改代码来支持一下
