### ISSUE TITLE
请问下云闪之鳞搜索不到BOSS

### ISSUE THREAD

**Issue by dadalala1999** [lazydog28/mc_auto_boss#42]
据观察，云闪之麟在索拉指南的第二页，需要往下滚动

**Comment by lazydog28** [comment]
https://github.com/lazydog28/mc_auto_boss/blob/b3f52de0de3a9a6666c818a8ebbbb577df97cbd2/background/utils.py#L129

脚本在未找到目标BOSS的情况下会自行往下滑动，如果未正常滑动，请再补充录屏或截图。如果是找不到BOSS，请检查配置文件内目标BOSS名称是否又错别字，可以少字但是不能错字
