### ISSUE TITLE
安装依赖时提示不存在 如图 还有我Windows Power Shell tab键不能补全 大佬知道是什么问题吗（命令似乎没错）

### ISSUE THREAD

**Issue by LYIFIDI** [lazydog28/mc_auto_boss#45]
![Uploading 屏幕截图 2024-06-07 153021.png…]()

**Comment by LYIFIDI** [comment]
![屏幕截图 2024-06-07 153021](https://github.com/lazydog28/mc_auto_boss/assets/162010125/a8e0580a-3c06-4a43-914c-1a13e6fac2ce)

**Comment by lazydog28** [comment]
你看一下你是不是嵌套文件夹里，在mc_auto_boss目录下面还有一个mc_auto_boss

**Comment by LYIFIDI** [comment]
> 你看一下你是不是嵌套文件夹里，在mc_auto_boss目录下面还有一个mc_auto_boss

感谢，已经解决了
