### ISSUE TITLE
请问大佬这个是什么bug

### ISSUE THREAD

**Issue by Keyformy** [lazydog28/mc_auto_boss#46]
![QQ图片20240607172354](https://github.com/lazydog28/mc_auto_boss/assets/171552293/e3b6f9dd-cbb6-4773-8d46-c14fa0059d0c)

**Comment by lazydog28** [comment]
游戏窗口截图，截图成功后删除截图的缓存。不知道啥原因导致bug

**Comment by Keyformy** [comment]
我也不是很明白，早上打开挂着就出门了，然后晚上回到家发现这个bug
