### ISSUE TITLE
无妄者副本搜索声骸bug

### ISSUE THREAD

**Issue by lemonydrop** [lazydog28/mc_auto_boss#48]
声骸就在前面但是一直在左右移动，导致超时而无法领取

**Comment by testpaper007** [comment]
补充一下，是因为声骸在角色身后，但是正好拾取不到，却被识别出来了，然后判定左右移动，但是不会向后移动，所以捡不到声骸

**Comment by lazydog28** [comment]
这个问题还真没有什么好办法，很难判断声骸是在身后还是面前。如果有好的判断方法可以补充
