### ISSUE TITLE
qq群问题

### ISSUE THREAD

**Issue by katsuraDaCn** [lazydog28/mc_auto_boss#49]
老哥，建议把之前那个群禁言，后面建的那个群开放禁言。前面那个群看着真的有点怕，感觉啥人都有，有可能有二逼会去录视频炫耀或者到处传播什么的。后面那个群应该都是从github来的，知道科学上网的人应该多多少少带点脑子，没有贬低别人的意思，但是是真的得考虑点这个的。

**Comment by lazydog28** [comment]
感谢你的建议，但是考虑了一下，水群水的多，突然换个群感觉怪怪的。后面的通知群不出问题就行，水群就算封了也就封了。至于传播这个问题，无论是禁言还是不禁言应该都没什么差别。
