### ISSUE TITLE
启动问题

### ISSUE THREAD

**Issue by dragon54004** [lazydog28/mc_auto_boss#5]
RuntimeError: (NotFound) Cannot open file C:\Users\周俊龙/.paddleocr/whl\det\ch\ch_PP-OCRv4_det_infer/inference.pdmodel, please confirm whether the file is normal.
  [Hint: Expected static_cast<bool>(fin.is_open()) == true, but received static_cast<bool>(fin.is_open()):0 != true:1.] 
提示我inference.pdmodel这个文件打不开
QAQ

**Comment by lazydog28** [comment]
你的用户名是中文导致无法加载模型，最新版本已经修复了
