### ISSUE TITLE
月卡奖励 识别完点击之后还有一个 90星声 的画面需要再次点击 现在会卡住

### ISSUE THREAD

**Issue by Yunako229** [lazydog28/mc_auto_boss#51]

**Comment by lazydog28** [comment]
90星声界面是啥样的
有哪些文字

**Comment by Yunako229** [comment]
那等等明天吧 现在没图片

**Comment by Yunako229** [comment]
![90f3a7b1b17f8ed0276c7b4946666fb6](https://github.com/lazydog28/mc_auto_boss/assets/84826080/8d401a13-a2f6-4b51-ac91-3d23858e2401)
这样的

**Comment by lazydog28** [comment]
好的 谢谢，我稍后加上该功能
