### ISSUE TITLE
正常运行几个小时后出现卡终端

### ISSUE THREAD

**Issue by Yunako229** [lazydog28/mc_auto_boss#53]
![bece2476fb1a3a656596fbbdfd7ae901_0](https://github.com/lazydog28/mc_auto_boss/assets/84826080/f95d621e-236b-48b4-a4a7-6c6876803a40)
人是在无妄者副本门口的 就是一直在开终端关终端循环

**Comment by lazydog28** [comment]
更新一下看还有没有这问题

**Comment by Yunako229** [comment]
![QQ截图20240609124848](https://github.com/lazydog28/mc_auto_boss/assets/84826080/c086f112-574e-466c-b97b-8d9f292ee85e)
还是有的

**Comment by Yunako229** [comment]
![QQ截图20240609124848](
![Uploading 519b8c50-0714-4cfc-b59a-127db4c95bbd.png…]()

**Comment by Yunako229** [comment]
![Uploading 519b8c50-0714-4cfc-b59a-127db4c95bbd.png…]()

**Comment by Yunako229** [comment]
![519b8c50-0714-4cfc-b59a-127db4c95bbd](https://github.com/lazydog28/mc_auto_boss/assets/84826080/dbca0685-dae5-4649-baf6-0bd45736983d)
