### ISSUE TITLE
大佬这是什么问题啊

### ISSUE THREAD

**Issue by LYIFIDI** [lazydog28/mc_auto_boss#56]
![a42ee17f31596f270f9b3db73b8ce52d](https://github.com/lazydog28/mc_auto_boss/assets/162010125/710b3dab-3af6-488e-8e4e-685a5228c67e)
![a42ee17f31596f270f9b3db73b8ce52d](https://github.com/lazydog28/mc_auto_boss/assets/162010125/710b3dab-3af6-488e-8e4e-685a5228c67e)
![a42ee17f31596f270f9b3db73b8ce52d](https://github.com/lazydog28/mc_auto_boss/assets/162010125/710b3dab-3af6-488e-8e4e-685a5228c67e)

**Comment by lazydog28** [comment]
你发的截图里有报错信息：which conflicts with any installable versions previously reported。

另外看你的截图，你之前有一个虚拟环境叫mc，然后你又尝试创建叫mc的虚拟环境，你拒绝了移除原有的环境，也就是之前的虚拟环境mc里面有的包和你现在要安装的 cudatoolkit=11.7 冲突

你paddlepaddle-gpu没装上，其他requirements.txt里的包你也没安装

**Comment by LYIFIDI** [comment]
> 你发的截图里有报错信息：这与之前报告的任何可安装版本冲突。
> 
> 另外看你的截图，你之前有一个虚拟环境叫mc，然后你又尝试创建叫mc的虚拟环境，你拒绝了移除原有的环境，也就是之前的虚拟环境mc里面有的包和你现在要安装的 cudatoolkit=11.7 冲突
> 
> 你paddlepaddle-gpu没装上，其他requirements.txt里的包你也没安装

那我现在该怎么办大佬，我想把之前的操作清掉重新弄一遍但是我不知道怎么搞

**Comment by lazydog28** [comment]
conda删除环境:https://blog.csdn.net/OOFFrankDura/article/details/106594349

**Comment by LYIFIDI** [comment]
> conda删除环境：https://blog.csdn.net/OOFFrankDura/article/details/106594349

感谢大佬

**Comment by LYIFIDI** [comment]
> conda删除环境：https://blog.csdn.net/OOFFrankDura/article/details/106594349

大佬，运行pip install -r .\requirements.txt后
提示
ERROR: Could not install packages due to an OSError: [WinError 5] 拒绝访问。: 'C:\\Users\\Administrator\\miniconda3\\envs\\mc\\Lib\\site-packages\\cv2\\opencv_videoio_ffmpeg460_64.dll'
Consider using the `--user` option or check the permissions.
咋搞啊用管理员身份运行了，还有csdn上说pip install -i http://pypi.dout试了也没用

**Comment by LYIFIDI** [comment]
![5{I$F)~7U@TVA(KB 8M`R54](https://github.com/lazydog28/mc_auto_boss/assets/162010125/29fd21e1-369e-40e8-967e-e85fa62d9fda)

**Comment by LYIFIDI** [comment]
![Image_1717876641309](https://github.com/lazydog28/mc_auto_boss/assets/162010125/6be05fb3-6286-4581-b85c-de8d96d18dc5)
大佬求救

**Comment by lazydog28** [comment]
你电脑里没有显卡嘛？

**Comment by LYIFIDI** [comment]
> 你电脑里没有显卡嘛？

![Image_1717901839805](https://github.com/lazydog28/mc_auto_boss/assets/162010125/cd806d5c-ab4c-4257-a550-abd69ee396b3)
用别的电脑一次就成功了，现在想换老版本也是一直提示·这个

> ![a42ee17f31596f270f9b3db73b8ce52d](https://private-user-images.githubusercontent.com/162010125/337915409-710b3dab-3af6-488e-8e4e-685a5228c67e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5MDIyMDYsIm5iZiI6MTcxNzkwMTkwNiwicGF0aCI6Ii8xNjIwMTAxMjUvMzM3OTE1NDA5LTcxMGIzZGFiLTNhZjYtNDg4ZS04ZTRlLTY4NWE1MjI4YzY3ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOVQwMjU4MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ODFkOWY1YzJhM2JlZDk3NzU4OWJmYjIxOWQ1MzY3ZDAxMmVkMDc0ZTM2NGRiMThhZTE5OTQ2MTY4YTJhMzY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vNdWupkj0er7yenZCVRo7tM49AOnbL4eoxiC-54FKqM) ![a42ee17f31596f270f9b3db73b8ce52d](https://private-user-images.githubusercontent.com/162010125/337915409-710b3dab-3af6-488e-8e4e-685a5228c67e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5MDIyMDYsIm5iZiI6MTcxNzkwMTkwNiwicGF0aCI6Ii8xNjIwMTAxMjUvMzM3OTE1NDA5LTcxMGIzZGFiLTNhZjYtNDg4ZS04ZTRlLTY4NWE1MjI4YzY3ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOVQwMjU4MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ODFkOWY1YzJhM2JlZDk3NzU4OWJmYjIxOWQ1MzY3ZDAxMmVkMDc0ZTM2NGRiMThhZTE5OTQ2MTY4YTJhMzY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vNdWupkj0er7yenZCVRo7tM49AOnbL4eoxiC-54FKqM) ![a42ee17f31596f270f9b3db73b8ce52d](https://private-user-images.githubusercontent.com/162010125/337915409-710b3dab-3af6-488e-8e4e-685a5228c67e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5MDIyMDYsIm5iZiI6MTcxNzkwMTkwNiwicGF0aCI6Ii8xNjIwMTAxMjUvMzM3OTE1NDA5LTcxMGIzZGFiLTNhZjYtNDg4ZS04ZTRlLTY4NWE1MjI4YzY3ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOVQwMjU4MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ODFkOWY1YzJhM2JlZDk3NzU4OWJmYjIxOWQ1MzY3ZDAxMmVkMDc0ZTM2NGRiMThhZTE5OTQ2MTY4YTJhMzY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vNdWupkj0er7yenZCVRo7tM49AOnbL4eoxiC-54FKqM)

**Comment by lazydog28** [comment]
应该是显卡版本太低，不支持cuda11.7   你参考paddlepaddle官网∶https://www.paddlepaddle.org.cn/

使用低版本的cuda试试
