### ISSUE TITLE
发现声骸到固定时间仍会进行下部操作

### ISSUE THREAD

**Issue by Zpy0826** [lazydog28/mc_auto_boss#57]
![`}E3~~XCB8X V$BMPCB G2V](https://github.com/lazydog28/mc_auto_boss/assets/49505736/d59600a6-c121-4e26-acf1-196c7f15598b)
![1717863833135](https://github.com/lazydog28/mc_auto_boss/assets/49505736/408f571f-3b25-4dac-8590-5ff175d7c78b)
可以加判断吗 吸收了再走或者发现了延长点时间

**Comment by lazydog28** [comment]
![image](https://github.com/lazydog28/mc_auto_boss/assets/55444285/62fcf8af-7797-4ae4-a63d-3016d04b6f0d)

吸收声骸的最大时间为你配置文件里最大空闲时间的一半或者10秒
