### ISSUE TITLE
关于2024年6月9日01:20:15的bug反馈

### ISSUE THREAD

**Issue by 1103962721** [lazydog28/mc_auto_boss#58]
2024年6月9日01:27:40 在此先感谢作者这几天的分享，辛苦作者。当前版本问题：
1.yolo模型训练还是不足，当然这庞大的数据集靠作者一个人来去标注上千上万张图片实在是太困难了，这方面我觉得群友是可以提供帮助的（有一定基础的群友，不然标注也是白瞎）
2.当前版本的无妄者，在传送至无妄者副本boss地区后，没有识别洞口按W的前进动作，也就导致了无法触发F进入副本的的条件，陷入超时的死循环。
3.再次，感谢分享

**Comment by lazydog28** [comment]
无妄者传送完成后先前走现在优化了，现在模型问题不是很大，能接受。但是无法判断声骸是不是在身后，这个没啥好主意我
