### ISSUE TITLE
体力不足时刷无妄者会一直循环

### ISSUE THREAD

**Issue by 1714775263** [lazydog28/mc_auto_boss#6]
![QQ截图20240603155443](https://github.com/lazydog28/mc_auto_boss/assets/45120294/ba9a2caa-9116-41c1-9c8d-3bcc432dcf07)
刷无妄者的话
这种情况是在体力不够的情况下存在的
出现这个就会一直循环

**Comment by lazydog28** [comment]
是最新的代码嘛？

**Comment by 1714775263** [comment]
> 是最新的代码嘛？

是的

**Comment by lazydog28** [comment]
我测试了一下 没有这个问题

**Comment by lazydog28** [comment]
讨论群：853749942

**Comment by 1714775263** [comment]
> 我测试了一下 没有这个问题

那就奇怪了
