### ISSUE TITLE
数据融合声骸合成时在获得声骸页面识别有问题

### ISSUE THREAD

**Issue by HrFirX** [lazydog28/mc_auto_boss#60]
日志截图如下，合成完成获得声骸页面时识别不到文本，尝试过换100缩放也还是报错
![屏幕截图 2024-06-09 055358](https://github.com/lazydog28/mc_auto_boss/assets/72868378/3da04183-603b-4baf-b927-644c3ea636cc)
![屏幕截图 2024-06-09 060009](https://github.com/lazydog28/mc_auto_boss/assets/72868378/2217fe74-2da8-4c13-b62c-8d955cc8384d)

**Comment by lazydog28** [comment]
是代码有bug 稍后修复

**Comment by lazydog28** [comment]
修复了
