### ISSUE TITLE
请问一下，更新的新模型战斗没结束就开始搜索声骸，然后去下一个boss了，是我设置出问题了吗

### ISSUE THREAD

**Issue by ZiShengCong** [lazydog28/mc_auto_boss#61]
用的暗卡唯，更新之前能有50吸收率，打的云闪，朔雷和无常。换了新模型之后打两套就开始搜索声骸，boss还没嘎，就溜了。求教

**Comment by lazydog28** [comment]
是最新的代码嘛？配置文件里空闲时间设置的多少？

**Comment by ZiShengCong** [comment]
下载的最新的
用的示例文件
刚又试了下也不行





滋生
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lazydog28/mc_auto_boss"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月9日(星期天) 上午10:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lazydog28/mc_auto_boss] 请问一下，更新的新模型战斗没结束就开始搜索声骸，然后去下一个boss了，是我设置出问题了吗 (Issue #61)





 
是最新的代码嘛？配置文件里空闲时间设置的多少？

**Comment by 1103962721** [comment]
2024年6月9日11:55:44 当前版本的模型声骸识别确实是有些问题，无妄者在脸上 原地转了一圈然后未识别到，目前本人用的最稳定的版本是6.8-6.9日的mc_auto_boss-master版本

**Comment by 1103962721** [comment]
然后就是这个版本不知道是占用高了，还是存在别的bug 刷完后会停顿很久不工作

**Comment by 1103962721** [comment]
> 2024年6月9日11:55:44 当前版本的模型声骸识别确实是有些问题，无妄者在脸上 原地转了一圈然后未识别到，目前本人用的最稳定的版本是6.8-6.9日的mc_auto_boss-master版本

2024年6月9日12:11:07 找到原因了，应该是代码方面的疏忽，识别通过右边cmd的反馈是可以看出来是成功识别到声骸的，这时候是不是应该执行类似于ret的语句 或者跳转至朝声骸移动并吸收的CALL（转圈->识别成功->w移动->成功吸收），作者大大的这个版本代码是转圈->识别成功->w移动->转圈->未找到->转圈->未找到->转圈->成功识别->时间超时

**Comment by 1103962721** [comment]
> 是最新的代码嘛？配置文件里空闲时间设置的多少？

希望作者可以看到这条的相关评论，作者辛苦。

**Comment by nightwishz** [comment]
> > 2024年6月9日11:55:44 当前版本的模型声骸识别确实是有些问题，无妄者在脸上 原地转了一圈然后未识别到，目前本人用的最稳定的版本是6.8-6.9日的mc_auto_boss-master版本
> 
> 2024年6月9日12:11:07 找到原因了，应该是代码方面的疏忽，识别通过右边cmd的反馈是可以看出来是成功识别到声骸的，这时候是不是应该执行类似于ret的语句 或者跳转至朝声骸移动并吸收的CALL（转圈->识别成功->w移动->成功吸收），作者大大的这个版本代码是转圈->识别成功->w移动->转圈->未找到->转圈->未找到->转圈->成功识别->时间超时

我也发现了，视角转的快了一点，导致识别出来的时候已经转过去了，就吸收不到了，可以加一个转视角停留2秒

**Comment by lazydog28** [comment]
好的，我下午有时间改一下代码

**Comment by lazydog28** [comment]
> > 2024年6月9日11:55:44 当前版本的模型声骸识别确实是有些问题，无妄者在脸上 原地转了一圈然后未识别到，目前本人用的最稳定的版本是6.8-6.9日的mc_auto_boss-master版本
> 
> 2024年6月9日12:11:07 找到原因了，应该是代码方面的疏忽，识别通过右边cmd的反馈是可以看出来是成功识别到声骸的，这时候是不是应该执行类似于ret的语句 或者跳转至朝声骸移动并吸收的CALL（转圈->识别成功->w移动->成功吸收），作者大大的这个版本代码是转圈->识别成功->w移动->转圈->未找到->转圈->未找到->转圈->成功识别->时间超时

代码逻和你不一致，现在的代码逻辑是先转圈找到目标，然后先进行水平移动，然后往前方走。如果在移动的过程当中发现找不到目标了才会再次进行转圈。就是说在理想情况下他只会转一次圈。如果发生多次转圈，说明在移动过程当中找不到目标了。

**Comment by lazydog28** [comment]
我又去看了一下源码，现在视角转动以后会等1秒再进行截图识别，如果觉得1秒低了，可以自行增加时间，如果没改过游戏设置的话，1秒理论上应该够了

https://github.com/lazydog28/mc_auto_boss/blob/359d1b77dd6833c3a54b2f5d1f5a266721be56b9/background/utils.py#L375
