### ISSUE TITLE
大佬这是什么问题

### ISSUE THREAD

**Issue by TFFtflas** [lazydog28/mc_auto_boss#67]
![image](https://github.com/lazydog28/mc_auto_boss/assets/156060529/72b2d436-1276-49f5-96ac-bce9a959e99a)

**Comment by lazydog28** [comment]
确定一下是否已经安装CUDA

[GPU环境搭建](https://github.com/lazydog28/mc_auto_boss/wiki/GPU%E7%8E%AF%E5%A2%83%E6%90%AD%E5%BB%BA)
