### ISSUE TITLE
最新版本的自动刷新会在200次左右出现报错，停止刷boss了，有很多人出现了同样的问题

### ISSUE THREAD

**Issue by maoshuo123456** [lazydog28/mc_auto_boss#68]
![UR} GUX)4{KWBKPV%~A7FEG_tmb](https://github.com/lazydog28/mc_auto_boss/assets/58798217/19d2fd9c-4270-473a-adcb-18382d871a4a)

**Comment by lazydog28** [comment]
已经添加释放截图资源的异常捕获
