### ISSUE TITLE
大佬，请问这是怎么回事呀

### ISSUE THREAD

**Issue by BIGNIII** [lazydog28/mc_auto_boss#69]
Could not load library cudnn_cnn_infer64_8.dll.Error code 1455

**Comment by BIGNIII** [comment]
![Uploading bfa.png…]()

**Comment by lazydog28** [comment]
没有安装cudnn

[GPU环境搭建](https://github.com/lazydog28/mc_auto_boss/wiki/GPU%E7%8E%AF%E5%A2%83%E6%90%AD%E5%BB%BA)
