### ISSUE TITLE
无妄者就在脸上不吸收直接退了

### ISSUE THREAD

**Issue by Keyformy** [lazydog28/mc_auto_boss#7]
![QA QB L(3({AB7`VBZ(8TS3](https://github.com/lazydog28/mc_auto_boss/assets/171552293/3909cc25-adcf-4e8f-9f98-1906bd78c43f)
声骸稍微远一点他就不吸收了，自己退😭

**Comment by lazydog28** [comment]
暂时没有做声骸目标识别的计划，等以后考虑优化

**Comment by Keyformy** [comment]
好的，谢谢大佬

**Comment by Get404code** [comment]
大佬，这种问题怎么解决？
Traceback (most recent call last):
File "D:\01Download\mc_auto_boss\background\utils.py", line 19, in <module>
from config import role
File "D:\01Download\mc_auto_boss\background\config.py", line 15, in <module>
class Config(BaseModel):
File "D:\01Download\mc_auto_boss\background\config.py", line 18, in Config
TargetBoss: list[str] = Field([], title="目标关键字")
TypeError: 'type' object is not subscriptable

**Comment by lazydog28** [comment]
> 大佬，这种问题怎么解决？ Traceback (most recent call last): File "D:\01Download\mc_auto_boss\background\utils.py", line 19, in from config import role File "D:\01Download\mc_auto_boss\background\config.py", line 15, in class Config(BaseModel): File "D:\01Download\mc_auto_boss\background\config.py", line 18, in Config TargetBoss: list[str] = Field([], title="目标关键字") TypeError: 'type' object is not subscriptable

你python版本多少？低于3.10的话用3.10的

**Comment by lsy0220** [comment]
大佬，可以加一下判断战斗结束后绕一圈捡声骸的功能吗？而且不是一直前进，因为击杀完boss后会面向前面完成后续攻击容易走到声骸前面或者侧面

**Comment by lazydog28** [comment]
dev分支当前已添加目标识别，拾取无妄者声骸功能，不稳定测试中
