### ISSUE TITLE
戰鬥判定修改的部分

### ISSUE THREAD

**Issue by edward07027** [lazydog28/mc_auto_boss#70]
能否詢問您戰鬥判定結束是從哪裡處理的嗎?
除了時間之外
自己有稍微改了一下utils.py
讓戰鬥模式變成
![1718018811542](https://github.com/lazydog28/mc_auto_boss/assets/129508263/bf79e14a-9417-432f-b2f6-d24512efdd83)
但是目前就是戰鬥結束無法停止，想詢問大佬有沒有想法

**Comment by lazydog28** [comment]
战斗是根据能否在画面里检测的`击败`这个词语，如果检测到则释放战斗逻辑直到本次战斗逻辑释放完毕。
