### ISSUE TITLE
按教程安装了，貌似还是不能启动

### ISSUE THREAD

**Issue by 18664249165** [lazydog28/mc_auto_boss#71]
按教程安装了，貌似还是不能启动
![screenshot-1718072076334](https://github.com/lazydog28/mc_auto_boss/assets/58971072/8a2f95a1-7311-423d-9980-2f1b2e3c7802)

**Comment by 18664249165** [comment]
卸载重新安装还是 不能启动。。求教。。

**Comment by lazydog28** [comment]
配置文件填写有问题

**Comment by lazydog28** [comment]
你配置文件截图发一下

**Comment by 18664249165** [comment]
![image](https://github.com/lazydog28/mc_auto_boss/assets/58971072/64b731ab-5e27-4474-b6e2-5585e1ab92fd)

**Comment by 18664249165** [comment]
DreamlessLevel: 40
DreamlessWaitTime: 5
FightTactics:
    - e~,q,r,a,0.1,a,0.1,a,0.1
    - e~,q,r,a,0.1,a,0.1,a,0.1
    - e~,q,r,a~,0.1,a~,0.1,a,0.1
MaxFightTime: 120
MaxIdleTime: 10
OcrInterval: 0.5
SearchDreamlessEchoes: true
SearchEchoes: false
SelectRoleInterval: 2
TargetBoss:
   - "辉萤军势"
   - "无常凶鹭"
   - "燎照之骑"

**Comment by lazydog28** [comment]
![image](https://github.com/lazydog28/mc_auto_boss/assets/55444285/072091e2-9b50-45c4-bac5-299618c7951a)
markdown格式下配置文件看不出来哪里有问题，截图上传吧


示例配置文件
```
MaxFightTime: 120 # 单次战斗最大时间 超过时间会进行下一个目标
MaxIdleTime: 10 # 战斗完成后的空闲时间，不能小于5
SelectRoleInterval: 2 # 选择角色的时间间隔 最小为2 避免无法选择角色
DreamlessLevel: 40 # 无妄者等级
DreamlessWaitTime: 3 # 进入无妄者后等待时间 不要超过战斗完成后的空闲时间的一半
SearchEchoes: true # 是否搜索声骸
SearchDreamlessEchoes: true # 是否搜索无妄者声骸
OcrInterval: 0 # OCR识别间隔时间
FightTactics: # 战斗策略 三个角色的释放技能顺序, 逗号分隔, e,q,r为技能, a为普攻, 数字为间隔时间,a~0.5为普攻按下0.5秒
    - "e,0.2,q,r,a,0.1,a,0.1,a,0.1,a,0.1,a,0.1"
    - "e,0.2,q,r,a,0.1,a,0.1,a,0.1,a,0.1,a,0.1"
    - "e,0.2,q,r,a,0.1,a,0.1,a,0.1,a,0.1,a~"
TargetBoss: # 目标BOSS 必须保证目标BOSS的位置是有借位信标的，可以少字但是不能有错别字
    - "鸣钟之龟"
    - "燎照之骑"
    - "聚械机偶"
    - "无妄者"
```

**Comment by lazydog28** [comment]
![image](https://github.com/lazydog28/mc_auto_boss/assets/55444285/c6e0575c-cf24-482a-af99-983e0e84c552)
