### ISSUE TITLE
声骸吸收问题

### ISSUE THREAD

**Issue by helloworld553** [lazydog28/mc_auto_boss#72]
作者好，在使用脚本吸收声骸发现世界boss打完有声骸可以吸收，但角色至少往前走了几步，离得远一些或者在身后就没有办法吸收，请问是什么问题啊？无妄者周本boss角色在吸收的时候好像可以转圈，世界boss就不行。

**Comment by lazydog28** [comment]
更新最新的代码

**Comment by helloworld553** [comment]
> 另外配置文件里是否配置了搜索声骸？
> 
> https://github.com/lazydog28/mc_auto_boss/blob/4bf77a3b06c5ff24d1de36063ec7b29cf1553284/config.example.yaml#L6

原来是没设置搜索，谢谢解答。
