### ISSUE TITLE
启动后不运行

### ISSUE THREAD

**Issue by iEclipseYe** [lazydog28/mc_auto_boss#73]
![e34cc7c6-cedf-48fa-a21c-7fe5adc6d8db](https://github.com/lazydog28/mc_auto_boss/assets/105561109/d1b41e41-d6da-49aa-bdae-f1699894ceb5)

**Comment by iEclipseYe** [comment]
![image](https://github.com/lazydog28/mc_auto_boss/assets/105561109/0e08654b-7f0e-4048-a7e8-763402532fd8)

**Comment by lazydog28** [comment]
没有安装cuda 

https://github.com/lazydog28/mc_auto_boss/wiki/GPU%E7%8E%AF%E5%A2%83%E6%90%AD%E5%BB%BA
