### ISSUE TITLE
希望加入定时重启游戏与脚本的功能，挂久了游戏崩了，脚本就停了

### ISSUE THREAD

**Issue by wang115t** [lazydog28/mc_auto_boss#74]

**Comment by wang115t** [comment]
![微信图片_20240611140140](https://github.com/lazydog28/mc_auto_boss/assets/61166529/38331e6e-8c00-4eb3-8148-d8235129156f)

**Comment by lazydog28** [comment]
暂时没有这方面的计划，如果是因为内存不足导致的游戏闪退，可以考虑安装一个内存清理软件，定时清理内存，如  [memreduct](https://memreduct.org/mem-reduct-download/)
