### ISSUE TITLE
建议加入定时重启游戏功能-防止挂久了游戏崩溃

### ISSUE THREAD

**Issue by wang115t** [lazydog28/mc_auto_boss#75]
![微信图片_20240611140140](https://github.com/lazydog28/mc_auto_boss/assets/61166529/bd157e87-debe-4386-be36-280e77bc4b90)

**Comment by lazydog28** [comment]
暂时没有这方面的计划，如果是因为内存不足导致的游戏闪退，可以考虑安装一个内存清理软件，定时清理内存，如 [memreduct](https://memreduct.org/mem-reduct-download/)
