### ISSUE TITLE
新的无妄者副本等级选择

### ISSUE THREAD

**Issue by OttyAI** [lazydog28/mc_auto_boss#77]
新版本更新后声骸与副本等级差距过大会导致副本不掉落声骸，建议在识别到提示窗口后选择更高一级无妄者本
<img width="640" alt="无妄者" src="https://github.com/lazydog28/mc_auto_boss/assets/147020514/d6e92b79-65eb-45c8-8791-13b173fe49f2">

**Comment by lazydog28** [comment]
配置文件里面可以自行配置无妄者副本等级。
