### ISSUE TITLE
因為沒開discussion，所以在issues中提醒開發者

### ISSUE THREAD

**Issue by jowilksasella** [lazydog28/mc_auto_boss#78]
先在這裡道個歉，開發者看到後可直接刪除。
因為沒有discussion，也沒有開發者的聯絡方式，故採取此方式。做成不便，敬請原諒。

閒魚已經看見倒狗了，若開發者有意抵制請盡快採取措施。

**Comment by lazydog28** [comment]
这个问题我也注意到了，但是开源项目被倒卖这个问题实在是想不出有什么好办法能避免。除非对代码进行加密，但这又违背了开源的初衷。倒卖就倒卖吧，就当购买的人付费购买了安装售后服务。
