### ISSUE TITLE
脚本运行几个小时时间就会这样，大佬能帮忙看看吗我百度不到。

### ISSUE THREAD

**Issue by Helikoj** [lazydog28/mc_auto_boss#80]
![34e931e0-6000-4fc7-9f2e-20adb7d344d3](https://github.com/lazydog28/mc_auto_boss/assets/89039177/1857fb3b-5c2e-410e-86a2-5fc5a0b37176)

**Comment by vertuer** [comment]
win32窗口失效，说明游戏窗体没了，被关闭了

**Comment by RoseRin0** [comment]
游戏崩溃了或者游戏闪退了，最新版本已有监控游戏窗口的改动。
