### ISSUE TITLE
战斗和吸收优化建议

### ISSUE THREAD

**Issue by ApocalypticDoctor** [lazydog28/mc_auto_boss#81]
有时候会被boss控 ,击飞什么的 ,战斗模板很容易乱掉(1号位用2/3号位的战斗模板 可以在每次攻击的时候都切换一下当前角色
     在utils.py中的第64行前加一句control.tap(str(info.roleIndex)) 就可以解决这个(也许)

   然后就是声骸吸收 虽然不清楚实现逻辑是怎么样的 但是吸收确实有点问题 比如 声骸在脸上不吸收什么的
   我想
            在战斗结束3s后扫描全屏 识别屏幕中声骸对应的RGB颜色
            如果有 返回颜色位置 和屏幕中心作比较 通过比较两个坐标位置进行移动
            如果没有 转动视角 2-3次即可
  这样的话 会不会效率搞一点呢？

**Comment by ApocalypticDoctor** [comment]
好像不太行 总之声骸吸收需要优化一下

**Comment by lazydog28** [comment]
https://github.com/lazydog28/mc_auto_boss/wiki/%E6%8E%A8%E8%8D%90%E6%B8%B8%E6%88%8F%E8%AE%BE%E7%BD%AE

**Comment by lazydog28** [comment]
声骸吸收当前基本上没有什么问题，如果不能正常识别到声骸进行吸收，请检查自己的游戏设置
