### ISSUE TITLE
这是什么情况啊

### ISSUE THREAD

**Issue by LYIFIDI** [lazydog28/mc_auto_boss#82]
![image](https://github.com/lazydog28/mc_auto_boss/assets/162010125/473b9c53-bbfe-4c4c-b71e-e9ac0736ce85)

**Comment by LYIFIDI** [comment]
![image](https://github.com/lazydog28/mc_auto_boss/assets/162010125/028e6370-afcb-49ad-ad91-a114c99799b1)
还有这个 未找到追踪

**Comment by lazydog28** [comment]
上面是没有检测到显卡，下面原因不知道，启动脚本后鼠标不要移动到游戏窗口内

[推荐游戏设置](https://github.com/lazydog28/mc_auto_boss/wiki/%E6%8E%A8%E8%8D%90%E6%B8%B8%E6%88%8F%E8%AE%BE%E7%BD%AE)

**Comment by LYIFIDI** [comment]
> 上面是没有检测到显卡，下面原因不知道，启动脚本后鼠标不要移动到游戏窗口内
> 
> [推荐游戏设置](https://github.com/lazydog28/mc_auto_boss/wiki/%E6%8E%A8%E8%8D%90%E6%B8%B8%E6%88%8F%E8%AE%BE%E7%BD%AE)

感谢大佬，下面情况遇到好几次了就是不会传送
