### ISSUE TITLE
突然就用不了了重新装也没用

### ISSUE THREAD

**Issue by LYIFIDI** [lazydog28/mc_auto_boss#86]
![屏幕截图 2024-06-16 221934](https://github.com/lazydog28/mc_auto_boss/assets/162010125/5b0cea33-3761-426a-ba00-8559343ab4dc)

**Comment by lazydog28** [comment]
依赖重新安装了？numpy的版本是多少？

**Comment by lazydog28** [comment]
看这个报错信息是numpy的版本高了
```
pip install numpy==1.26.4
```

**Comment by LYIFIDI** [comment]
> 依赖重新安装了？numpy的版本是多少？
我发现问题了，安装依赖时自动安装了最新版
pip install --upgrade --force-reinstall numpy==1.26.4
就好了，不好意思·麻烦了
