### ISSUE TITLE
启动脚本时找不到游戏窗口

### ISSUE THREAD

**Issue by Peppa-g** [lazydog28/mc_auto_boss#9]
当前角色状态：Status.idle 未找到游戏窗口

游戏设置 1280*720 窗口模式 缩放为100% python版本312

![123](https://github.com/lazydog28/mc_auto_boss/assets/171573368/0151ed32-ffb2-4ed2-9cd9-112121c894e5)

**Comment by Peppa-g** [comment]
这个问题已经解决 没有离boss足够近

但是

![image](https://github.com/lazydog28/mc_auto_boss/assets/171573368/6ecc9cb8-8305-4b78-b105-00eb05365683)

**Comment by lazydog28** [comment]
在项目根目录运行脚本，即执行： python background/main.py

**Comment by Peppa-g** [comment]
![image](https://github.com/lazydog28/mc_auto_boss/assets/171573368/29e23c6a-4989-418a-a620-672e77b52327)

目录应该不是问题的原因，我已经修改background下的config.yaml，使用的是example的内容，改运行目录也是一样的结果

**Comment by Peppa-g** [comment]
前面是因为修改目录重新建了一个空config，因为没填写内容先报错了，让我误以为解决了未找到游戏窗口的问题

**Comment by lazydog28** [comment]
不支持外服

**Comment by lazydog28** [comment]
游戏窗口名称应该是 鸣潮，这个不是中文
