### ISSUE TITLE
一直卡追踪

### ISSUE THREAD

**Issue by xiaoyige-png** [lazydog28/mc_auto_boss#90]
开了刷之后一直追踪不到锚点

**Comment by lazydog28** [comment]
截图上传

**Comment by xiaoyige-png** [comment]
![Uploading KZVN1NZ$`DC$}3(H069S~]6.png…]()

**Comment by xiaoyige-png** [comment]
![KZVN1NZDC$}3(H069S~ 6](https://github.com/lazydog28/mc_auto_boss/assets/173051584/3dc41e29-ff5e-4e1b-ac2d-4f2ad11828d6)

**Comment by RoseRin0** [comment]
#98 更新到此修复pr，或回退到前一个版本试试。

**Comment by RoseRin0** [comment]
请确认以下项目：
1.脚本是否能正常通过F2查找到BOSS并点击探测后打开地图。
2.脚本打开地图后游戏画面右侧是否会自动弹出BOSS信息，且你能在右下角看到追踪二字。
3.看到探测之后，脚本是否点击了一个位置之后导致地图右侧BOSS信息界面消失。
