### ISSUE TITLE
攻击机制

### ISSUE THREAD

**Issue by ApocalypticDoctor** [lazydog28/mc_auto_boss#95]
为什么有时候攻击的时候普攻不连贯(间隔为0.1s
为什么打败boss后还会继续攻击

**Comment by RoseRin0** [comment]
#101 调整了连招方式，可更新至最新版本试试

**Comment by RoseRin0** [comment]
普攻连贯性问题已解决，单个角色连招结束后才会进行是否已经击败的判断（暂不考虑改写此逻辑）。
