### ISSUE TITLE
无法识别到残像探寻

### ISSUE THREAD

**Issue by user599** [lazydog28/mc_auto_boss#97]
过去我一直使用2560*1440的分辨率全屏，一直没有问题。
今天更新后无论是全屏2560*1440还是窗口化的1280*720都点不到残像探寻的位置
前者会一直点击漂泊日志，后者会一直点击强者之路
1. 1280*720（窗口）
![image](https://github.com/lazydog28/mc_auto_boss/assets/41457884/0631659e-6e6a-4e6a-b270-6fe9ead7bad9)
2. 2560*1440（全屏）
![image](https://github.com/lazydog28/mc_auto_boss/assets/41457884/a82ab81b-ac23-4774-a139-b37d9c9f5058)

**Comment by user599** [comment]
补充一下，就算在页面上自己手动纠正到残像探寻，也没能正确识别到boss

**Comment by Wangzifu98** [comment]
回退到添加偏移前的那个版本

**Comment by user599** [comment]
> 回退到添加偏移前的那个版本

谢谢，这样确实解决了

**Comment by RoseRin0** [comment]
#98 已修复，待合并。
